import assert from "node:assert/strict";
import { createElement } from "react";
import test from "node:test";
import { createDomHarness } from "./support/dom.js";

test("MCP Turn off/on pins the displayed revision, preserves errors until refresh, and distinguishes sign-in from enablement", async (t) => {
  const dom = await createDomHarness();
  const originalFetch = globalThis.fetch;
  t.after(async () => { await dom.cleanup(); globalThis.fetch = originalFetch; });
  const { IncludedMcpSetup } = await import("../web-local/src/components/panes/IncludedMcpSetup.js");
  let server = { scope: "project", name: "Fixture service", revision: "a".repeat(64), disabled: false, transport: "http", endpoint: "https://example.invalid/mcp", auth: "automatic", credential: "missing", environmentKeys: [], headerKeys: [] };
  const calls: any[] = [];
  globalThis.fetch = async (_input, init) => {
    const body = JSON.parse(String(init?.body)); calls.push(body);
    assert.equal(body.spaceId, "space-fixture");
    if (body.operation === "open") return Response.json({ sessionId: "setup-fixture", servers: [server] });
    assert.equal(body.sessionId, "setup-fixture");
    if (body.operation === "close") return Response.json({ closed: true });
    if (body.operation === "list") return Response.json({ servers: [server] });
    assert.equal(body.operation, "enabled"); assert.equal(body.scope, "project"); assert.equal(body.name, server.name);
    assert.equal(typeof body.enabled, "boolean");
    if (body.expectedRevision !== server.revision) return Response.json({ error: "This service changed. Refresh connections before continuing." }, { status: 409 });
    server = { ...server, disabled: !body.enabled, revision: (body.enabled ? "d" : "b").repeat(64) };
    return Response.json({ servers: [server] });
  };
  const button = (text: string) => { const found = [...dom.container.querySelectorAll("button")].find(item => item.textContent === text); assert.ok(found, `Missing ${text}`); return found; };
  await dom.render(createElement(IncludedMcpSetup, { spaceId: "space-fixture", enabled: true }));
  await dom.waitFor(() => dom.container.textContent?.includes("Turn off") === true);
  assert.match(dom.container.textContent!, /Not signed in/);
  assert.doesNotMatch(dom.container.textContent!, /Sign-in required|Sign in required/);
  await dom.act(() => button("Turn off").click());
  await dom.waitFor(() => dom.container.textContent?.includes("Turned off") === true);
  assert.equal(button("Check").disabled, true);
  assert.equal(button("Sign in").disabled, true);
  assert.deepEqual(calls.at(-1), { scope: "project", name: server.name, expectedRevision: "a".repeat(64), enabled: false, spaceId: "space-fixture", sessionId: "setup-fixture", operation: "enabled" });
  server = { ...server, revision: "c".repeat(64) };
  await dom.act(() => button("Turn on").click());
  await dom.waitFor(() => !!dom.container.querySelector('[role="alert"]'));
  assert.match(dom.container.querySelector('[role="alert"]')!.textContent!, /service changed/);
  assert.equal(server.disabled, true);
  assert.equal(calls.at(-1).expectedRevision, "b".repeat(64));
  await dom.act(() => button("Refresh").click());
  await dom.waitFor(() => !dom.container.querySelector('[role="alert"]'));
  await dom.act(() => button("Turn on").click());
  await dom.waitFor(() => dom.container.textContent?.includes("Turn off") === true);
  assert.equal(calls.at(-1).expectedRevision, "c".repeat(64)); assert.equal(calls.at(-1).enabled, true);
  assert.equal(button("Check").disabled, false);
  assert.match(dom.container.textContent!, /Not signed in/);
  await dom.render(createElement(IncludedMcpSetup, { spaceId: "space-fixture", enabled: false }));
  assert.equal(button("Turn off").disabled, true, "a disabled Extension cannot change its native connection");
});
