/**
 * File and folder icons for Files, attachments, and file details.
 *
 * Every glyph comes from vscode-icons (MIT), drawn in its own colors; several
 * types also carry a light-theme variant. A few vscode-icons drawings are too
 * heavy for a Files row (the generator caps each glyph at 12 KB), so those
 * types use their language's or family's icon instead (Cargo → Rust,
 * Composer → PHP, LICENSE → text). Glyph ids are `vs:<name>`. A type
 * vscode-icons does not draw gets its closest general icon (text, image,
 * archive, config, and so on).
 *
 * The SVG data is vendored in `file-icons-data.ts`, which
 * `scripts/generate-file-icons.mjs` regenerates from the ids used below. After
 * adding or changing a glyph id here, rerun that script.
 *
 * work-folders are deliberately plain: every folder gets the same closed and open
 * glyph, whatever its name, so no folder looks special.
 */
import { fileIconGlyphs, type FileIconGlyph } from "./file-icons-data";

export { fileIconArtworkMarkup } from "./file-icons-data";

export interface FileTreeIconSpec {
  /** Vendored glyph id, for example `vs:file-type-docker`. */
  glyph: string;
  label: string;
}

function icon(glyph: string, label: string): FileTreeIconSpec {
  return { glyph, label };
}

const fallbackFileIcon = icon("vs:default-file", "File");
const closedFolderIcon = icon("vs:default-folder", "Folder");
const openFolderIcon = icon("vs:default-folder-opened", "Open folder");

// ---------------------------------------------------------------------------
// Icon kinds. Each kind is one glyph and label; the tables below map
// file names and extensions onto these kinds.
// ---------------------------------------------------------------------------

const kinds = {
  // Programming languages
  ada: icon("vs:file-type-ada", "Ada file"),
  apl: icon("vs:file-type-apl", "APL file"),
  applescript: icon("vs:file-type-applescript", "AppleScript file"),
  arduino: icon("vs:file-type-arduino", "Arduino sketch"),
  assembly: icon("vs:file-type-assembly", "Assembly file"),
  autohotkey: icon("vs:file-type-autohotkey", "AutoHotkey script"),
  autoit: icon("vs:file-type-autoit", "AutoIt script"),
  awk: icon("vs:file-type-awk", "AWK script"),
  c: icon("vs:file-type-c", "C file"),
  cHeader: icon("vs:file-type-cheader", "C header"),
  cairo: icon("vs:file-type-cairo", "Cairo file"),
  clojure: icon("vs:file-type-clojure", "Clojure file"),
  clojurescript: icon("vs:file-type-clojurescript", "ClojureScript file"),
  cobol: icon("vs:file-type-cobol", "COBOL file"),
  coffeescript: icon("vs:file-type-coffeescript", "CoffeeScript file"),
  commonLisp: icon("vs:file-type-lisp", "Lisp file"),
  cpp: icon("vs:file-type-cpp", "C++ file"),
  cppHeader: icon("vs:file-type-cppheader", "C++ header"),
  crystal: icon("vs:file-type-crystal", "Crystal file"),
  csharp: icon("vs:file-type-csharp", "C# file"),
  cuda: icon("vs:file-type-cuda", "CUDA file"),
  cython: icon("vs:file-type-cython", "Cython file"),
  d: icon("vs:file-type-dlang", "D file"),
  dart: icon("vs:file-type-dartlang", "Dart file"),
  delphi: icon("vs:file-type-delphi", "Delphi form"),
  elixir: icon("vs:file-type-elixir", "Elixir file"),
  elm: icon("vs:file-type-elm", "Elm file"),
  emacsLisp: icon("vs:file-type-emacs", "Emacs Lisp file"),
  erlang: icon("vs:file-type-erlang", "Erlang file"),
  fortran: icon("vs:file-type-fortran", "Fortran file"),
  fsharp: icon("vs:file-type-fsharp", "F# file"),
  gdscript: icon("vs:file-type-gdscript", "Godot file"),
  gleam: icon("vs:file-type-gleam", "Gleam file"),
  go: icon("vs:file-type-go", "Go file"),
  groovy: icon("vs:file-type-groovy", "Groovy file"),
  haskell: icon("vs:file-type-haskell", "Haskell file"),
  haxe: icon("vs:file-type-haxe", "Haxe file"),
  java: icon("vs:file-type-java", "Java file"),
  julia: icon("vs:file-type-julia", "Julia file"),
  kotlin: icon("vs:file-type-kotlin", "Kotlin file"),
  livescript: icon("vs:file-type-livescript", "LiveScript file"),
  lua: icon("vs:file-type-lua", "Lua file"),
  luau: icon("vs:file-type-luau", "Luau file"),
  matlab: icon("vs:file-type-matlab", "MATLAB file"),
  nasm: icon("vs:file-type-assembly", "NASM assembly file"),
  nim: icon("vs:file-type-nim", "Nim file"),
  objectiveC: icon("vs:file-type-objectivec", "Objective-C or MATLAB file"),
  ocaml: icon("vs:file-type-ocaml", "OCaml file"),
  odin: icon("vs:default-file", "Odin file"),
  pascal: icon("vs:file-type-delphi", "Pascal file"),
  perl: icon("vs:file-type-perl", "Perl file"),
  php: icon("vs:file-type-php", "PHP file"),
  python: icon("vs:file-type-python", "Python file"),
  pythonStub: icon("vs:file-type-python", "Python type stub"),
  r: icon("vs:file-type-r", "R file"),
  racket: icon("vs:file-type-racket", "Racket file"),
  raku: icon("vs:file-type-raku", "Raku file"),
  reason: icon("vs:file-type-reason", "Reason file"),
  rescript: icon("vs:file-type-rescript", "ReScript file"),
  ruby: icon("vs:file-type-ruby", "Ruby file"),
  rust: icon("vs:file-type-rust", "Rust file"),
  scala: icon("vs:file-type-scala", "Scala file"),
  scheme: icon("vs:file-type-lisp", "Scheme file"),
  shader: icon("vs:file-type-glsl", "Shader file"),
  metal: icon("vs:file-type-metal", "Metal shader"),
  solidity: icon("vs:file-type-solidity", "Solidity file"),
  swift: icon("vs:file-type-swift", "Swift file"),
  systemVerilog: icon("vs:file-type-systemverilog", "SystemVerilog file"),
  tcl: icon("vs:file-type-tcl", "Tcl file"),
  v: icon("vs:file-type-verilog", "V or Verilog file"),
  vhdl: icon("vs:file-type-vhdl", "VHDL file"),
  visualBasic: icon("vs:file-type-vb", "Visual Basic file"),
  vyper: icon("vs:file-type-vyper", "Vyper file"),
  webassembly: icon("vs:file-type-wasm", "WebAssembly file"),
  zig: icon("vs:file-type-zig", "Zig file"),
  abap: icon("vs:default-file", "ABAP file"),

  // JavaScript and TypeScript
  javascript: icon("vs:file-type-js", "JavaScript file"),
  javascriptMin: icon("vs:file-type-js", "Minified JavaScript file"),
  javascriptTest: icon("vs:file-type-testjs", "JavaScript test"),
  typescript: icon("vs:file-type-typescript", "TypeScript file"),
  typescriptDeclaration: icon("vs:file-type-typescriptdef", "TypeScript declarations"),
  typescriptTest: icon("vs:file-type-testts", "TypeScript test"),
  jsx: icon("vs:file-type-reactjs", "React JavaScript file"),
  tsx: icon("vs:file-type-reactts", "React TypeScript file"),
  reactTest: icon("vs:file-type-testts", "React test"),
  storybook: icon("vs:file-type-storybook", "Storybook stories"),
  sourceMap: icon("vs:file-type-map", "Source map"),
  jsConfig: icon("vs:file-type-jsconfig", "JavaScript config"),
  tsConfig: icon("vs:file-type-tsconfig", "TypeScript config"),

  // Other tests
  goTest: icon("vs:file-type-go", "Go test"),
  pythonTest: icon("vs:file-type-pytest", "Python test"),
  rubySpec: icon("vs:file-type-rspec", "RSpec test"),
  rustTest: icon("vs:file-type-rust", "Rust test"),

  // Web pages, templates, and frameworks
  html: icon("vs:file-type-html", "HTML file"),
  astro: icon("vs:file-type-astro", "Astro component"),
  svelte: icon("vs:file-type-svelte", "Svelte component"),
  vue: icon("vs:file-type-vue", "Vue component"),
  angular: icon("vs:file-type-angular", "Angular config"),
  mdx: icon("vs:file-type-mdx", "MDX file"),
  erb: icon("vs:file-type-erb", "Embedded Ruby template"),
  ejs: icon("vs:file-type-ejs", "EJS template"),
  haml: icon("vs:file-type-haml", "Haml template"),
  handlebars: icon("vs:file-type-handlebars", "Handlebars template"),
  jinja: icon("vs:file-type-jinja", "Jinja template"),
  liquid: icon("vs:file-type-liquid", "Liquid template"),
  marko: icon("vs:file-type-marko", "Marko template"),
  mjml: icon("vs:file-type-mjml", "MJML email template"),
  mustache: icon("vs:file-type-mustache", "Mustache template"),
  nunjucks: icon("vs:file-type-nunjucks", "Nunjucks template"),
  pug: icon("vs:file-type-pug", "Pug template"),
  razor: icon("vs:file-type-razor", "Razor template"),
  twig: icon("vs:file-type-twig", "Twig template"),
  velocity: icon("vs:file-type-velocity", "Velocity template"),
  freemarker: icon("vs:file-type-freemarker", "FreeMarker template"),
  blade: icon("vs:file-type-blade", "Blade template"),
  elixirTemplate: icon("vs:file-type-eex", "Elixir template"),
  template: icon("vs:default-file", "Template file"),
  webShortcut: icon("vs:file-type-http", "Web shortcut"),
  link: icon("vs:file-type-lnk", "Shortcut"),

  // Styles
  css: icon("vs:file-type-css", "CSS file"),
  cssModule: icon("vs:file-type-css", "CSS module"),
  sass: icon("vs:file-type-scss", "Sass file"),
  less: icon("vs:file-type-less", "Less file"),
  stylus: icon("vs:file-type-stylus", "Stylus file"),
  postcss: icon("vs:file-type-css", "PostCSS file"),

  // Data and databases
  json: icon("vs:file-type-json", "JSON file"),
  jsonLines: icon("vs:file-type-json", "JSON Lines file"),
  json5: icon("vs:file-type-json5", "JSON5 file"),
  jsonLd: icon("vs:file-type-jsonld", "JSON-LD file"),
  hjson: icon("vs:file-type-hjson", "Hjson file"),
  yaml: icon("vs:file-type-yaml", "YAML file"),
  toml: icon("vs:file-type-toml", "TOML file"),
  xml: icon("vs:file-type-xml", "XML file"),
  rss: icon("vs:file-type-rss", "Feed file"),
  graphql: icon("vs:file-type-graphql", "GraphQL file"),
  protobuf: icon("vs:file-type-protobuf", "Protocol Buffers file"),
  prisma: icon("vs:file-type-prisma", "Prisma schema"),
  sql: icon("vs:file-type-sql", "SQL file"),
  database: icon("vs:file-type-db", "Database file"),
  sqlite: icon("vs:file-type-sqlite", "SQLite database"),
  access: icon("vs:file-type-access", "Access database"),
  parquet: icon("vs:file-type-parquet", "Parquet data"),
  avro: icon("vs:file-type-avro", "Avro data"),
  arrow: icon("vs:file-type-parquet", "Arrow data"),
  numpy: icon("vs:file-type-numpy", "NumPy data"),
  pickle: icon("vs:file-type-python", "Pickle data"),
  rdata: icon("vs:file-type-r", "R data"),
  stata: icon("vs:file-type-stata", "Stata data"),
  mapData: icon("vs:file-type-geojson", "Map data"),
  jupyter: icon("vs:file-type-jupyter", "Jupyter notebook"),
  rmarkdown: icon("vs:file-type-rmd", "R Markdown file"),
  dhall: icon("vs:file-type-dhall", "Dhall file"),
  jsonnet: icon("vs:file-type-jsonnet", "Jsonnet file"),
  binaryData: icon("vs:file-type-binary", "Data file"),
  mermaid: icon("vs:file-type-mermaid", "Mermaid diagram"),
  graphviz: icon("vs:file-type-graphviz", "Graphviz diagram"),
  plantuml: icon("vs:file-type-plantuml", "PlantUML diagram"),
  apiBlueprint: icon("vs:file-type-apib", "API Blueprint"),
  raml: icon("vs:file-type-raml", "RAML API definition"),
  openapi: icon("vs:file-type-swagger", "OpenAPI definition"),

  // Spreadsheets
  csv: icon("vs:file-type-csv", "CSV file"),
  tsv: icon("vs:file-type-csv", "TSV file"),
  excel: icon("vs:file-type-excel", "Excel spreadsheet"),
  excelTemplate: icon("vs:file-type-excel", "Excel template"),
  numbers: icon("vs:file-type-excel", "Numbers spreadsheet"),
  odfSheet: icon("vs:file-type-libreoffice-calc", "OpenDocument spreadsheet"),

  // Documents
  word: icon("vs:file-type-word", "Word document"),
  wordTemplate: icon("vs:file-type-word", "Word template"),
  odfText: icon("vs:file-type-libreoffice-writer", "OpenDocument text"),
  pages: icon("vs:file-type-word", "Pages document"),
  richText: icon("vs:file-type-word", "Rich text document"),
  xps: icon("vs:file-type-pdf", "XPS document"),
  oneNote: icon("vs:file-type-onenote", "OneNote notebook"),
  project: icon("vs:default-file", "Project plan"),
  ebook: icon("vs:file-type-epub", "E-book"),
  latex: icon("vs:file-type-tex", "LaTeX file"),
  bibtex: icon("vs:file-type-tex", "BibTeX bibliography"),
  postscript: icon("vs:file-type-postscript", "PostScript file"),
  screenplay: icon("vs:file-type-text", "Fountain screenplay"),
  finalDraft: icon("vs:file-type-text", "Final Draft screenplay"),

  // Presentations
  powerpoint: icon("vs:file-type-powerpoint", "PowerPoint presentation"),
  powerpointTemplate: icon("vs:file-type-powerpoint", "PowerPoint template"),
  keynote: icon("vs:file-type-powerpoint", "Keynote presentation"),
  odfSlides: icon("vs:file-type-libreoffice-impress", "OpenDocument presentation"),

  // PDF
  pdf: icon("vs:file-type-pdf", "PDF document"),

  // Plain text and documentation
  text: icon("vs:file-type-text", "Text file"),
  markdown: icon("vs:file-type-markdown", "Markdown file"),
  restructuredText: icon("vs:file-type-text", "reStructuredText file"),
  asciidoc: icon("vs:file-type-asciidoc", "AsciiDoc file"),
  orgMode: icon("vs:file-type-org", "Org file"),
  textile: icon("vs:file-type-textile", "Textile file"),
  mediawiki: icon("vs:file-type-wikitext", "Wiki markup file"),
  creole: icon("vs:file-type-text", "Creole file"),
  pod: icon("vs:file-type-text", "Perl documentation"),
  manpage: icon("vs:file-type-text", "Manual page"),
  log: icon("vs:file-type-log", "Log file"),
  diff: icon("vs:file-type-diff", "Diff file"),
  patch: icon("vs:file-type-diff", "Patch file"),
  subtitles: icon("vs:file-type-video", "Subtitles"),
  calendar: icon("vs:file-type-text", "Calendar file"),
  contact: icon("vs:file-type-text", "Contact card"),
  email: icon("vs:file-type-text", "Email message"),
  outlook: icon("vs:file-type-outlook", "Outlook message"),
  readme: icon("vs:file-type-text", "Readme"),
  license: icon("vs:file-type-text", "License"),
  changelog: icon("vs:file-type-text", "Changelog"),
  contributing: icon("vs:file-type-text", "Contributing guide"),
  codeOfConduct: icon("vs:file-type-text", "Code of conduct"),
  security: icon("vs:file-type-cert", "Security policy"),
  authors: icon("vs:file-type-text", "Authors"),
  todo: icon("vs:file-type-todo", "To-do list"),
  robots: icon("vs:file-type-robots", "Robots file"),

  // AI instructions and prompts
  agentInstructions: icon("vs:file-type-agents", "Agent instructions"),
  claudeInstructions: icon("vs:file-type-claude", "Claude instructions"),
  copilotInstructions: icon("vs:file-type-copilot", "Copilot instructions"),
  cursorRules: icon("vs:file-type-cursorrules", "Cursor rules"),
  skill: icon("vs:file-type-skill", "Skill instructions"),
  prompt: icon("vs:file-type-ai", "Prompt file"),
  mcpConfig: icon("vs:file-type-mcp", "MCP server config"),
  llmsText: icon("vs:file-type-ai", "LLM site guide"),

  // Images
  image: icon("vs:file-type-image", "Image file"),
  rawPhoto: icon("vs:file-type-image", "Raw photo"),
  iconImage: icon("vs:file-type-favicon", "Icon image"),
  svg: icon("vs:file-type-svg", "SVG image"),
  openexr: icon("vs:file-type-image", "OpenEXR image"),

  // Design, 3D, and CAD
  photoshop: icon("vs:file-type-photoshop", "Photoshop document"),
  illustrator: icon("vs:file-type-ai", "Illustrator artwork"),
  indesign: icon("vs:file-type-image", "InDesign document"),
  xd: icon("vs:file-type-image", "Adobe XD design"),
  figma: icon("vs:file-type-image", "Figma design"),
  sketch: icon("vs:file-type-sketch", "Sketch design"),
  affinity: icon("vs:file-type-affinitydesigner", "Affinity document"),
  gimp: icon("vs:file-type-gimp", "GIMP image"),
  krita: icon("vs:file-type-krita", "Krita image"),
  coreldraw: icon("vs:file-type-image", "CorelDRAW drawing"),
  omnigraffle: icon("vs:file-type-image", "OmniGraffle diagram"),
  drawio: icon("vs:file-type-drawio", "draw.io diagram"),
  visio: icon("vs:file-type-image", "Visio diagram"),
  inkscape: icon("vs:file-type-svg", "Inkscape drawing"),
  model3d: icon("vs:file-type-binary", "3D model"),
  blender: icon("vs:file-type-blender", "Blender scene"),
  fbx: icon("vs:file-type-fbx", "FBX model"),
  gltf: icon("vs:file-type-gltf", "glTF model"),
  max3ds: icon("vs:file-type-binary", "3ds Max scene"),
  maya: icon("vs:file-type-maya", "Maya scene"),
  cinema4d: icon("vs:file-type-binary", "Cinema 4D scene"),
  houdini: icon("vs:file-type-binary", "Houdini scene"),
  zbrush: icon("vs:file-type-binary", "ZBrush file"),
  sketchup: icon("vs:file-type-binary", "SketchUp model"),
  rhino: icon("vs:file-type-binary", "Rhino model"),
  openscad: icon("vs:file-type-openscad", "OpenSCAD model"),
  autocad: icon("vs:file-type-binary", "CAD drawing"),
  autodesk: icon("vs:file-type-binary", "Fusion design"),
  cadModel: icon("vs:file-type-binary", "CAD model"),
  kicad: icon("vs:file-type-binary", "KiCad design"),
  eagle: icon("vs:file-type-binary", "EAGLE circuit design"),
  pointCloud: icon("vs:file-type-binary", "Point cloud"),
  lightwave: icon("vs:file-type-binary", "LightWave model"),
  unity: icon("vs:default-file", "Unity file"),
  unreal: icon("vs:default-file", "Unreal Engine file"),
  godotScene: icon("vs:file-type-tscn", "Godot scene"),
  pico8: icon("vs:default-file", "PICO-8 cartridge"),
  scratch: icon("vs:default-file", "Scratch project"),
  minecraft: icon("vs:file-type-minecraft", "Minecraft data"),
  interfaceBuilder: icon("vs:file-type-xib", "Interface Builder file"),

  // Fonts
  font: icon("vs:file-type-font", "Font file"),
  bitmapFont: icon("vs:file-type-font", "Bitmap font"),
  fontforge: icon("vs:file-type-font", "FontForge project"),
  glyphs: icon("vs:file-type-glyphs", "Glyphs font source"),
  ufo: icon("vs:file-type-font", "UFO font source"),

  // Audio and video
  audio: icon("vs:file-type-audio", "Audio file"),
  midi: icon("vs:file-type-audio", "MIDI file"),
  audacity: icon("vs:file-type-audio", "Audacity project"),
  musescore: icon("vs:file-type-audio", "MuseScore score"),
  lilypond: icon("vs:file-type-lilypond", "LilyPond score"),
  video: icon("vs:file-type-video", "Video file"),
  matroska: icon("vs:file-type-video", "Matroska video"),
  afterEffects: icon("vs:file-type-video", "After Effects project"),
  premiere: icon("vs:file-type-video", "Premiere Pro project"),

  // Archives, packages, and disk images
  archive: icon("vs:file-type-zip", "Archive file"),
  brotli: icon("vs:file-type-zip", "Brotli archive"),
  installer: icon("vs:file-type-package", "Installer package"),
  javaArchive: icon("vs:file-type-jar", "Java archive"),
  pythonPackage: icon("vs:file-type-python", "Python package"),
  pythonCompiled: icon("vs:file-type-python", "Compiled Python"),
  rubyGem: icon("vs:file-type-ruby", "Ruby gem"),
  nugetPackage: icon("vs:file-type-nuget", "NuGet package"),
  rustCrate: icon("vs:file-type-rust", "Rust crate"),
  androidPackage: icon("vs:file-type-zip", "Android package"),
  vscodeExtension: icon("vs:file-type-vsix", "VS Code extension"),
  electronArchive: icon("vs:file-type-electron", "Electron archive"),
  diskImage: icon("vs:file-type-binary", "Disk image"),
  virtualMachine: icon("vs:file-type-binary", "Virtual machine image"),
  vmwareDisk: icon("vs:file-type-binary", "VMware disk"),

  // Shells and scripts
  shell: icon("vs:file-type-shell", "Shell script"),
  bash: icon("vs:file-type-shell", "Bash script"),
  zsh: icon("vs:file-type-zsh", "Zsh script"),
  fish: icon("vs:file-type-shell", "Fish script"),
  powershell: icon("vs:file-type-powershell", "PowerShell script"),
  batch: icon("vs:file-type-bat", "Batch script"),
  automator: icon("vs:file-type-applescript", "Automator workflow"),
  bashConfig: icon("vs:file-type-shell", "Bash settings"),
  zshConfig: icon("vs:file-type-zsh", "Zsh settings"),
  vim: icon("vs:file-type-vim", "Vim settings"),
  tmux: icon("vs:file-type-tmux", "tmux settings"),

  // Security
  certificate: icon("vs:file-type-cert", "Certificate"),
  privateKey: icon("vs:file-type-cert", "Key file"),
  publicKey: icon("vs:file-type-cert", "Public key"),
  keystore: icon("vs:file-type-cert", "Keystore"),
  signature: icon("vs:file-type-gpg", "Signature"),
  passwordDatabase: icon("vs:file-type-cert", "Password database"),
  sshKey: icon("vs:file-type-cert", "SSH key"),
  credentials: icon("vs:file-type-cert", "Credentials file"),

  // Binaries
  binary: icon("vs:file-type-binary", "Binary file"),
  executable: icon("vs:file-type-binary", "Program"),
  library: icon("vs:file-type-binary", "Library"),
  objectFile: icon("vs:file-type-binary", "Object file"),
  backup: icon("vs:file-type-bak", "Backup file"),
  temporary: icon("vs:default-file", "Temporary file"),

  // Configuration and tooling
  config: icon("vs:file-type-config", "Settings file"),
  editorconfig: icon("vs:file-type-editorconfig", "EditorConfig file"),
  dotenv: icon("vs:file-type-dotenv", "Environment settings"),
  lockfile: icon("vs:file-type-config", "Lock file"),
  ignore: icon("vs:file-type-config", "Ignore file"),
  git: icon("vs:file-type-git", "Git file"),
  mercurial: icon("vs:file-type-mercurial", "Mercurial file"),
  codeowners: icon("vs:file-type-codeowners", "Code owners"),
  githubActions: icon("vs:file-type-yaml", "GitHub Actions workflow"),
  dependabot: icon("vs:file-type-dependabot", "Dependabot config"),
  npm: icon("vs:file-type-npm", "npm package file"),
  npmConfig: icon("vs:file-type-npm", "npm config"),
  npmLock: icon("vs:file-type-npm", "npm lockfile"),
  yarn: icon("vs:file-type-yarn", "Yarn file"),
  pnpm: icon("vs:file-type-pnpm", "pnpm file"),
  bun: icon("vs:file-type-bun", "Bun file"),
  deno: icon("vs:file-type-deno", "Deno file"),
  node: icon("vs:file-type-node", "Node.js version"),
  vite: icon("vs:file-type-vite", "Vite config"),
  vitest: icon("vs:file-type-vitest", "Vitest config"),
  webpack: icon("vs:file-type-webpack", "webpack config"),
  rollup: icon("vs:file-type-rollup", "Rollup config"),
  esbuild: icon("vs:file-type-esbuild", "esbuild config"),
  swc: icon("vs:file-type-swc", "SWC config"),
  babel: icon("vs:file-type-babel", "Babel config"),
  tailwind: icon("vs:file-type-tailwind", "Tailwind config"),
  postcssConfig: icon("vs:file-type-css", "PostCSS config"),
  jest: icon("vs:file-type-jest", "Jest config"),
  playwright: icon("vs:file-type-playwright", "Playwright config"),
  cypress: icon("vs:file-type-cypress", "Cypress config"),
  karma: icon("vs:file-type-karma", "Karma config"),
  mocha: icon("vs:file-type-mocha", "Mocha config"),
  istanbul: icon("vs:file-type-nyc", "Coverage config"),
  prettier: icon("vs:file-type-prettier", "Prettier config"),
  eslint: icon("vs:file-type-eslint", "ESLint config"),
  stylelint: icon("vs:file-type-stylelint", "Stylelint config"),
  biome: icon("vs:file-type-biome", "Biome config"),
  browserslist: icon("vs:file-type-browserslist", "Browserslist config"),
  commitlint: icon("vs:file-type-commitlint", "commitlint config"),
  lefthook: icon("vs:file-type-lefthook", "Lefthook config"),
  precommit: icon("vs:file-type-precommit", "pre-commit config"),
  husky: icon("vs:file-type-husky", "Husky hook"),
  renovate: icon("vs:file-type-renovate", "Renovate config"),
  markdownlint: icon("vs:file-type-markdownlint", "markdownlint config"),
  yamllint: icon("vs:file-type-yamllint", "yamllint config"),
  shellcheck: icon("vs:file-type-shellcheck", "ShellCheck config"),
  clang: icon("vs:file-type-clangd", "Clang config"),
  nextjs: icon("vs:file-type-next", "Next.js config"),
  nuxt: icon("vs:file-type-nuxt", "Nuxt config"),
  remix: icon("vs:file-type-config", "Remix config"),
  gatsby: icon("vs:file-type-gatsby", "Gatsby config"),
  svelteConfig: icon("vs:file-type-svelteconfig", "Svelte config"),
  astroConfig: icon("vs:file-type-astroconfig", "Astro config"),
  vueConfig: icon("vs:file-type-vueconfig", "Vue config"),
  turborepo: icon("vs:file-type-turbo", "Turborepo config"),
  nx: icon("vs:file-type-nx", "Nx config"),
  lerna: icon("vs:file-type-json", "Lerna config"),
  nodemon: icon("vs:file-type-nodemon", "nodemon config"),
  pm2: icon("vs:file-type-pm2", "PM2 config"),
  storybookConfig: icon("vs:file-type-storybook", "Storybook config"),
  docker: icon("vs:file-type-docker", "Dockerfile"),
  dockerCompose: icon("vs:file-type-docker", "Docker Compose file"),
  dockerIgnore: icon("vs:file-type-docker", "Docker ignore file"),
  kubernetes: icon("vs:file-type-config", "Kubernetes config"),
  helm: icon("vs:file-type-helm", "Helm chart"),
  terraform: icon("vs:file-type-terraform", "Terraform file"),
  nomad: icon("vs:file-type-config", "Nomad job"),
  ansible: icon("vs:file-type-ansible", "Ansible config"),
  vagrant: icon("vs:file-type-vagrant", "Vagrantfile"),
  nix: icon("vs:file-type-nix", "Nix file"),
  make: icon("vs:file-type-shell", "Makefile"),
  cmake: icon("vs:file-type-cmake", "CMake file"),
  meson: icon("vs:file-type-meson", "Meson build file"),
  bazel: icon("vs:file-type-bazel", "Bazel build file"),
  justfile: icon("vs:file-type-just", "Justfile"),
  gradle: icon("vs:file-type-gradle", "Gradle build file"),
  maven: icon("vs:file-type-maven", "Maven project"),
  sbt: icon("vs:file-type-sbt", "sbt build file"),
  leiningen: icon("vs:file-type-clojure", "Leiningen project"),
  cargo: icon("vs:file-type-rust", "Cargo manifest"),
  cargoLock: icon("vs:file-type-rust", "Cargo lockfile"),
  rustToolchain: icon("vs:file-type-rust-toolchain", "Rust toolchain"),
  goModule: icon("vs:file-type-go-package", "Go module"),
  goSum: icon("vs:file-type-go-package", "Go checksums"),
  pythonConfig: icon("vs:file-type-pythonconfig", "Python project config"),
  pythonRequirements: icon("vs:file-type-pip", "Python requirements"),
  pythonVersion: icon("vs:file-type-pyenv", "Python version"),
  pytest: icon("vs:file-type-pytest", "pytest config"),
  pipenv: icon("vs:file-type-pip", "Pipenv file"),
  poetry: icon("vs:file-type-poetry", "Poetry lockfile"),
  uv: icon("vs:file-type-uv", "uv lockfile"),
  conda: icon("vs:file-type-conda", "Conda environment"),
  rubyConfig: icon("vs:file-type-ruby", "Ruby config"),
  rubyVersion: icon("vs:file-type-ruby", "Ruby version"),
  bundler: icon("vs:file-type-ruby", "Bundler file"),
  rake: icon("vs:file-type-rake", "Rakefile"),
  rubocop: icon("vs:file-type-rubocop", "RuboCop config"),
  rspecConfig: icon("vs:file-type-rspec", "RSpec config"),
  cocoapods: icon("vs:file-type-config", "CocoaPods file"),
  carthage: icon("vs:file-type-config", "Carthage file"),
  swiftPackage: icon("vs:file-type-swift", "Swift package"),
  composer: icon("vs:file-type-php", "Composer file"),
  mix: icon("vs:file-type-elixir", "Mix project"),
  rebar: icon("vs:file-type-erlang", "rebar config"),
  haskellConfig: icon("vs:file-type-haskell", "Haskell project config"),
  cabal: icon("vs:file-type-cabal", "Cabal file"),
  flutter: icon("vs:file-type-flutter", "Flutter project"),
  homebrew: icon("vs:file-type-brew", "Brewfile"),
  dotnetProject: icon("vs:file-type-csproj", ".NET project"),
  vscode: icon("vs:file-type-vscode", "VS Code workspace"),
  sublime: icon("vs:file-type-sublime", "Sublime Text project"),
  devcontainer: icon("vs:file-type-devcontainer", "Dev container config"),
  gitpod: icon("vs:file-type-gitpod", "Gitpod config"),
  tilt: icon("vs:file-type-tiltfile", "Tiltfile"),
  goreleaser: icon("vs:file-type-config", "GoReleaser config"),
  dvc: icon("vs:file-type-dvc", "DVC file"),
  readthedocs: icon("vs:file-type-readthedocs", "Docs build config"),
  jekyll: icon("vs:file-type-jekyll", "Jekyll config"),
  hugo: icon("vs:file-type-hugo", "Hugo config"),
  netlify: icon("vs:file-type-netlify", "Netlify config"),
  vercel: icon("vs:file-type-vercel", "Vercel config"),
  firebase: icon("vs:file-type-firebase", "Firebase config"),
  heroku: icon("vs:file-type-procfile", "Procfile"),
  cloudflare: icon("vs:file-type-cloudflare", "Cloudflare Workers config"),
  serverless: icon("vs:file-type-serverless", "Serverless config"),
  travis: icon("vs:file-type-travis", "Travis CI config"),
  gitlab: icon("vs:file-type-gitlab", "GitLab CI config"),
  circleci: icon("vs:file-type-circleci", "CircleCI config"),
  azurePipelines: icon("vs:file-type-azurepipelines", "Azure Pipelines config"),
  jenkins: icon("vs:file-type-jenkins", "Jenkinsfile"),
  codecov: icon("vs:file-type-codecov", "Codecov config"),
  sentry: icon("vs:file-type-sentry", "Sentry config"),
  snyk: icon("vs:file-type-snyk", "Snyk policy"),
  sonarqube: icon("vs:file-type-config", "SonarQube config"),
  nginx: icon("vs:file-type-nginx", "nginx config"),
  caddy: icon("vs:file-type-caddy", "Caddyfile"),
  apache: icon("vs:file-type-apache", "Apache config"),
  watchman: icon("vs:file-type-watchmanconfig", "Watchman config"),
  finder: icon("vs:file-type-config", "Finder metadata"),
  desktopEntry: icon("vs:file-type-config", "Desktop entry"),
  curlConfig: icon("vs:file-type-shell", "curl config"),
  wgetConfig: icon("vs:file-type-shell", "Wget config"),
  gemConfig: icon("vs:file-type-ruby", "RubyGems config"),

  // Additional types drawn by vscode-icons
  objectiveCpp: icon("vs:file-type-objectivecpp", "Objective-C++ file"),
  hlsl: icon("vs:file-type-hlsl", "HLSL shader"),
  wgsl: icon("vs:file-type-wgsl", "WGSL shader"),
  vba: icon("vs:file-type-vba", "VBA macro"),
  apex: icon("vs:file-type-apex", "Apex file"),
  al: icon("vs:file-type-al", "AL file"),
  ballerina: icon("vs:file-type-ballerina", "Ballerina file"),
  bicep: icon("vs:file-type-bicep", "Bicep template"),
  cadence: icon("vs:file-type-cadence", "Cadence file"),
  capnp: icon("vs:file-type-capnp", "Cap'n Proto schema"),
  cddl: icon("vs:file-type-cddl", "CDDL schema"),
  circom: icon("vs:file-type-circom", "Circom circuit"),
  dylan: icon("vs:file-type-dylan", "Dylan file"),
  grain: icon("vs:file-type-grain", "Grain file"),
  huff: icon("vs:file-type-huff", "Huff file"),
  idris: icon("vs:file-type-idris", "Idris file"),
  io: icon("vs:file-type-io", "Io file"),
  janet: icon("vs:file-type-janet", "Janet file"),
  k: icon("vs:file-type-k", "K file"),
  lean: icon("vs:file-type-lean", "Lean file"),
  mojo: icon("vs:file-type-mojo", "Mojo file"),
  nushell: icon("vs:file-type-nushell", "Nushell script"),
  pony: icon("vs:file-type-pony", "Pony file"),
  prolog: icon("vs:file-type-prolog", "Prolog file"),
  purescript: icon("vs:file-type-purescript", "PureScript file"),
  q: icon("vs:file-type-q", "Q file"),
  qsharp: icon("vs:file-type-qsharp", "Q# file"),
  red: icon("vs:file-type-red", "Red file"),
  rexx: icon("vs:file-type-rexx", "REXX script"),
  slang: icon("vs:file-type-s-lang", "S-Lang file"),
  squirrel: icon("vs:file-type-squirrel", "Squirrel file"),
  teal: icon("vs:file-type-teal", "Teal file"),
  toit: icon("vs:file-type-toit", "Toit file"),
  uiua: icon("vs:file-type-uiua", "Uiua file"),
  unison: icon("vs:file-type-unison", "Unison file"),
  vala: icon("vs:file-type-vala", "Vala file"),
  vapi: icon("vs:file-type-vapi", "Vala API file"),
  vlang: icon("vs:file-type-vlang", "V script"),
  wolfram: icon("vs:file-type-wolfram", "Wolfram file"),
  wurst: icon("vs:file-type-wurst", "Wurst file"),
  yang: icon("vs:file-type-yang", "YANG model"),
  kusto: icon("vs:file-type-kusto", "Kusto query"),
  sparql: icon("vs:file-type-sparql", "SPARQL query"),
  xquery: icon("vs:file-type-xquery", "XQuery file"),
  plsql: icon("vs:file-type-plsql", "PL/SQL file"),
  pgsql: icon("vs:file-type-pgsql", "PostgreSQL file"),
  templ: icon("vs:file-type-templ", "templ component"),
  slint: icon("vs:file-type-slint", "Slint file"),
  qml: icon("vs:file-type-qml", "QML file"),
  smarty: icon("vs:file-type-smarty", "Smarty template"),
  slim: icon("vs:file-type-html", "Slim template"),
  lolcode: icon("vs:file-type-lolcode", "LOLCODE file"),
  pawn: icon("vs:file-type-pawn", "Pawn file"),
  sas: icon("vs:file-type-sas", "SAS program"),
  stan: icon("vs:file-type-stan", "Stan model"),
  tablegen: icon("vs:file-type-tablegen", "TableGen file"),
  ttcn: icon("vs:file-type-ttcn", "TTCN-3 file"),
  lsl: icon("vs:file-type-lsl", "LSL script"),
  maxscript: icon("vs:file-type-maxscript", "MAXScript file"),
  powerQuery: icon("vs:file-type-mlang", "Power Query file"),
  powerbi: icon("vs:file-type-powerbi", "Power BI report"),
  nearley: icon("vs:file-type-nearly", "Nearley grammar"),
  lark: icon("vs:file-type-lark", "Lark grammar"),
  antlr: icon("vs:file-type-antlr", "ANTLR grammar"),
  yacc: icon("vs:file-type-yacc", "Yacc grammar"),
  lex: icon("vs:file-type-lex", "Lex file"),
  flatbuffers: icon("vs:file-type-flatbuffers", "FlatBuffers schema"),
  dbml: icon("vs:file-type-dbml", "DBML schema"),
  edge: icon("vs:file-type-edge", "Edge template"),
  tera: icon("vs:file-type-tera", "Tera template"),
  vento: icon("vs:file-type-vento", "Vento template"),
  glimmer: icon("vs:file-type-glimmer", "Glimmer component"),
  imba: icon("vs:file-type-imba", "Imba file"),
  riot: icon("vs:file-type-riot", "Riot component"),
  san: icon("vs:file-type-san", "San component"),
  uvue: icon("vs:file-type-uvue", "uni-app component"),
  wxml: icon("vs:file-type-wxml", "WXML template"),
  wxss: icon("vs:file-type-wxss", "WXSS style"),
  dust: icon("vs:file-type-dustjs", "Dust template"),
  jbuilder: icon("vs:file-type-jbuilder", "Jbuilder template"),
  vanillaExtract: icon("vs:file-type-vanilla-extract", "vanilla-extract style"),
  cssMap: icon("vs:file-type-cssmap", "CSS source map"),
  jsMap: icon("vs:file-type-jsmap", "JavaScript source map"),
  jestSnapshot: icon("vs:file-type-jest-snapshot", "Jest snapshot"),
  tsBuildInfo: icon("vs:file-type-tsbuildinfo", "TypeScript build info"),
  cypressSpec: icon("vs:file-type-cypress-spec", "Cypress test"),
  ngComponent: icon("vs:file-type-ng-component-ts", "Angular component"),
  ngComponentJs: icon("vs:file-type-ng-component-js", "Angular component"),
  ngComponentHtml: icon("vs:file-type-ng-component-html", "Angular template"),
  ngComponentCss: icon("vs:file-type-ng-component-css", "Angular component style"),
  ngComponentScss: icon("vs:file-type-ng-component-scss", "Angular component style"),
  ngComponentLess: icon("vs:file-type-ng-component-less", "Angular component style"),
  ngComponentSass: icon("vs:file-type-ng-component-sass", "Angular component style"),
  ngService: icon("vs:file-type-ng-service-ts", "Angular service"),
  ngModule: icon("vs:file-type-ng-module-ts", "Angular module"),
  ngDirective: icon("vs:file-type-ng-directive-ts", "Angular directive"),
  ngPipe: icon("vs:file-type-ng-pipe-ts", "Angular pipe"),
  ngGuard: icon("vs:file-type-ng-guard-ts", "Angular guard"),
  ngRouting: icon("vs:file-type-ng-routing-ts", "Angular routes"),
  ngInterceptor: icon("vs:file-type-ng-interceptor-ts", "Angular interceptor"),
  jsonSchema: icon("vs:file-type-json-schema", "JSON Schema"),
  geojson: icon("vs:file-type-geojson", "GeoJSON file"),
  safetensors: icon("vs:file-type-safetensors", "Model weights"),
  duckdb: icon("vs:file-type-duckdb", "DuckDB database"),
  cypher: icon("vs:file-type-neo4j", "Cypher query"),
  sqlProject: icon("vs:file-type-sqlproj", "SQL project"),
  xsl: icon("vs:file-type-xsl", "XSL stylesheet"),
  dtd: icon("vs:file-type-dtd", "Document type definition"),
  xliff: icon("vs:file-type-xliff", "Translation file"),
  xaml: icon("vs:file-type-xaml", "XAML file"),
  odfDrawing: icon("vs:file-type-libreoffice-draw", "OpenDocument drawing"),
  odfFormula: icon("vs:file-type-libreoffice-math", "OpenDocument formula"),
  odfDatabase: icon("vs:file-type-libreoffice-base", "OpenDocument database"),
  infopath: icon("vs:file-type-infopath", "InfoPath form"),
  eps: icon("vs:file-type-eps", "EPS image"),
  quarto: icon("vs:file-type-quarto", "Quarto document"),
  http: icon("vs:file-type-http", "HTTP request file"),
  rest: icon("vs:file-type-rest", "REST request file"),
  hurl: icon("vs:file-type-hurl", "Hurl file"),
  bruno: icon("vs:file-type-bruno", "Bruno request"),
  ron: icon("vs:file-type-ron", "RON file"),
  registry: icon("vs:file-type-registry", "Registry file"),
  systemd: icon("vs:file-type-systemd", "systemd unit"),
  ovpn: icon("vs:file-type-ovpn", "OpenVPN profile"),
  gettext: icon("vs:file-type-text", "Translation catalog"),
  hunspell: icon("vs:file-type-hunspell", "Spelling dictionary"),
  godotUid: icon("vs:file-type-gduid", "Godot UID"),
  shaderlab: icon("vs:file-type-shaderlab", "Unity shader"),
  n64: icon("vs:file-type-n64", "Nintendo 64 ROM"),
  gcode: icon("vs:file-type-gcode", "G-code file"),
  fritzing: icon("vs:file-type-fritzing", "Fritzing sketch"),
  gamemaker: icon("vs:file-type-gamemaker", "GameMaker project"),
  aseprite: icon("vs:file-type-aseprite", "Aseprite sprite"),
  excalidraw: icon("vs:file-type-excalidraw", "Excalidraw drawing"),
  affinityPhoto: icon("vs:file-type-affinityphoto", "Affinity Photo document"),
  affinityPublisher: icon("vs:file-type-affinitypublisher", "Affinity Publisher document"),
  flashSource: icon("vs:file-type-fla", "Flash source"),
  flash: icon("vs:file-type-flash", "Flash movie"),
  javaClass: icon("vs:file-type-class", "Java class"),
  debian: icon("vs:file-type-debian", "Debian package"),
  bats: icon("vs:file-type-bats", "Bats test"),
  powershellModule: icon("vs:file-type-powershell-psm", "PowerShell module"),
  powershellData: icon("vs:file-type-powershell-psd", "PowerShell data file"),
  powershellFormat: icon("vs:file-type-powershell-format", "PowerShell format file"),
  powershellTypes: icon("vs:file-type-powershell-types", "PowerShell types file"),
  ini: icon("vs:file-type-ini", "INI settings"),
  poml: icon("vs:file-type-poml", "POML prompt"),
  avif: icon("vs:file-type-avif", "AVIF image"),
  webp: icon("vs:file-type-webp", "WebP image"),
  opentofu: icon("vs:file-type-opentofu", "OpenTofu file"),
  hcl: icon("vs:file-type-hashicorp", "HCL file"),
  packer: icon("vs:file-type-packer", "Packer template"),
  ninja: icon("vs:file-type-ninja", "Ninja build file"),
  manifest: icon("vs:file-type-manifest", "Web app manifest"),
  taskfile: icon("vs:file-type-taskfile", "Taskfile"),
  earthly: icon("vs:file-type-earthly", "Earthfile"),
  taplo: icon("vs:file-type-taplo", "Taplo config"),
  cspell: icon("vs:file-type-cspell", "CSpell config"),
  commitizen: icon("vs:file-type-commitizen", "Commitizen config"),
  semanticRelease: icon("vs:file-type-semanticrelease", "semantic-release config"),
  knip: icon("vs:file-type-knip", "Knip config"),
  syncpack: icon("vs:file-type-syncpack", "Syncpack config"),
  stryker: icon("vs:file-type-stryker", "Stryker config"),
  wallaby: icon("vs:file-type-wallaby", "Wallaby config"),
  wdio: icon("vs:file-type-wdio", "WebdriverIO config"),
  testcafe: icon("vs:file-type-testcafe", "TestCafe config"),
  tslint: icon("vs:file-type-tslint", "TSLint config"),
  jshint: icon("vs:file-type-jshint", "JSHint config"),
  jsbeautify: icon("vs:file-type-jsbeautify", "JS Beautify config"),
  htmlhint: icon("vs:file-type-htmlhint", "HTMLHint config"),
  csscomb: icon("vs:file-type-csscomb", "CSScomb config"),
  csslint: icon("vs:file-type-csslint", "CSSLint config"),
  coffeelint: icon("vs:file-type-coffeelint", "CoffeeLint config"),
  textlint: icon("vs:file-type-textlint", "textlint config"),
  markuplint: icon("vs:file-type-markuplint", "markuplint config"),
  vale: icon("vs:file-type-vale", "Vale config"),
  doxygen: icon("vs:file-type-doxyfile", "Doxygen config"),
  typedoc: icon("vs:file-type-typedoc", "TypeDoc config"),
  tsdoc: icon("vs:file-type-tsdoc", "TSDoc config"),
  docusaurus: icon("vs:file-type-docusaurus", "Docusaurus config"),
  eleventy: icon("vs:file-type-eleventy", "Eleventy config"),
  quasar: icon("vs:file-type-quasar", "Quasar config"),
  ionic: icon("vs:file-type-ionic", "Ionic config"),
  capacitor: icon("vs:file-type-capacitor", "Capacitor config"),
  tauri: icon("vs:file-type-tauri", "Tauri config"),
  electronBuilder: icon("vs:file-type-electron", "Electron config"),
  eas: icon("vs:file-type-eas-metadata", "EAS config"),
  unocss: icon("vs:file-type-unocss", "UnoCSS config"),
  windi: icon("vs:file-type-windi", "Windi CSS config"),
  pandacss: icon("vs:file-type-pandacss", "Panda CSS config"),
  tamagui: icon("vs:file-type-tamagui", "Tamagui config"),
  drizzle: icon("vs:file-type-drizzle-orm", "Drizzle config"),
  knex: icon("vs:file-type-knex", "Knex config"),
  sequelize: icon("vs:file-type-sequelize", "Sequelize config"),
  convex: icon("vs:file-type-convex", "Convex config"),
  parcel: icon("vs:file-type-parcel", "Parcel config"),
  rspack: icon("vs:file-type-rspack", "Rspack config"),
  rolldown: icon("vs:file-type-rolldown", "Rolldown config"),
  tsdown: icon("vs:file-type-tsdown", "tsdown config"),
  craco: icon("vs:file-type-craco", "CRACO config"),
  metro: icon("vs:file-type-metro", "Metro config"),
  purgecss: icon("vs:file-type-purgecss", "PurgeCSS config"),
  svgo: icon("vs:file-type-svgo", "SVGO config"),
  flyio: icon("vs:file-type-flyio", "Fly.io config"),
  railway: icon("vs:file-type-railway", "Railway config"),
  renderConfig: icon("vs:file-type-render", "Render config"),
  codemagic: icon("vs:file-type-codemagic", "Codemagic config"),
  bitbucket: icon("vs:file-type-bitbucketpipeline", "Bitbucket Pipelines config"),
  appveyor: icon("vs:file-type-appveyor", "AppVeyor config"),
  drone: icon("vs:file-type-drone", "Drone CI config"),
  trivy: icon("vs:file-type-trivy", "Trivy config"),
  checkov: icon("vs:file-type-checkov", "Checkov config"),
  mise: icon("vs:file-type-mise", "mise config"),
  direnv: icon("vs:file-type-direnv", "direnv file"),
  devenv: icon("vs:file-type-devenv", "devenv config"),
  doppler: icon("vs:file-type-doppler", "Doppler config"),
  funding: icon("vs:file-type-funding", "Funding info"),
  publiccode: icon("vs:file-type-publiccode", "publiccode file"),
  reuse: icon("vs:file-type-reuse", "REUSE config"),
  allContributors: icon("vs:file-type-allcontributors", "All Contributors config"),
  unlicense: icon("vs:file-type-unlicense", "Unlicense"),
  godotProject: icon("vs:file-type-godot", "Godot project"),
  dbt: icon("vs:file-type-dbt", "dbt project"),
  pulumi: icon("vs:file-type-pulumi", "Pulumi project"),
  geminiInstructions: icon("vs:file-type-gemini", "Gemini instructions"),
  coderabbit: icon("vs:file-type-coderabbit", "CodeRabbit config"),
  opencode: icon("vs:file-type-opencode", "OpenCode config"),
  humans: icon("vs:file-type-humanstxt", "Humans file"),
  sitemap: icon("vs:file-type-sitemap", "Sitemap"),
  gcloud: icon("vs:file-type-gcloud", "Google Cloud config"),
  pixi: icon("vs:file-type-pixi", "Pixi project"),
  pdm: icon("vs:file-type-pdm", "PDM file"),
  ruff: icon("vs:file-type-ruff", "Ruff config"),
  mypy: icon("vs:file-type-mypy", "mypy config"),
  tox: icon("vs:file-type-tox", "tox config"),
  bazelIgnore: icon("vs:file-type-bazel-ignore", "Bazel ignore file"),
  bazelVersion: icon("vs:file-type-bazel-version", "Bazel version"),
  goWork: icon("vs:file-type-go-work", "Go workspace"),
  golangci: icon("vs:file-type-golangci", "golangci-lint config"),
  buf: icon("vs:file-type-buf", "Buf config"),
  bunfig: icon("vs:file-type-bunfig", "Bun config"),
  rome: icon("vs:file-type-rome", "Rome config"),
  oxlint: icon("vs:file-type-oxlint", "Oxlint config"),
  jsr: icon("vs:file-type-jsr", "JSR package file"),
  lintStaged: icon("vs:file-type-lintstagedrc", "lint-staged config"),
  nanostaged: icon("vs:file-type-nanostaged", "nano-staged config"),
  xcode: icon("vs:file-type-xcode", "Xcode file"),
  storyboard: icon("vs:file-type-storyboard", "Storyboard"),
  wasp: icon("vs:file-type-wasp", "Wasp file"),
  prismaConfig: icon("vs:file-type-prismaconfig", "Prisma config"),
  graphqlConfig: icon("vs:file-type-graphql-config", "GraphQL config"),
  codegen: icon("vs:file-type-codegen", "GraphQL codegen config"),
  npmPackageJsonLint: icon("vs:file-type-npmpackagejsonlint", "npm-package-json-lint config"),
  changelogen: icon("vs:file-type-changelogen", "changelogen config"),
  vscodeTest: icon("vs:file-type-vscode-test", "VS Code test config"),
  nestjs: icon("vs:file-type-nestjs", "NestJS config"),
  expo: icon("vs:file-type-expo", "Expo config"),
  denoify: icon("vs:file-type-denoify", "Denoify config"),
} satisfies Record<string, FileTreeIconSpec>;

type IconKind = keyof typeof kinds;

// ---------------------------------------------------------------------------
// Extensions. Keys may be compound (`d.ts`, `tar.gz`, `test.tsx`); the longest
// matching compound extension wins. Values list space-separated extensions.
// ---------------------------------------------------------------------------

const extensionGroups: Array<[IconKind, string]> = [
  // Programming languages
  ["abap", "abap"],
  ["ada", "ada adb ads"],
  ["apl", "apl dyalog"],
  ["applescript", "applescript scpt scptd"],
  ["arduino", "ino pde"],
  ["assembly", "asm s a51 inc65"],
  ["autohotkey", "ahk"],
  ["autoit", "au3"],
  ["awk", "awk gawk"],
  ["c", "c"],
  ["cHeader", "h"],
  ["cairo", "cairo"],
  ["clojure", "clj cljc edn"],
  ["clojurescript", "cljs"],
  ["cobol", "cob cbl cpy"],
  ["coffeescript", "coffee litcoffee cson iced"],
  ["commonLisp", "lisp lsp cl fasl"],
  ["cpp", "cpp cc cxx c++ cp cppm ixx"],
  ["cppHeader", "hpp hh hxx h++ ipp tpp inl"],
  ["crystal", "cr"],
  ["csharp", "cs csx"],
  ["cuda", "cu cuh"],
  ["cython", "pyx pxd pxi"],
  ["d", "d di"],
  ["dart", "dart"],
  ["delphi", "dfm dpr"],
  ["elixir", "ex exs"],
  ["elixirTemplate", "eex heex leex"],
  ["elm", "elm"],
  ["emacsLisp", "el elc"],
  ["erlang", "erl hrl"],
  ["fortran", "f f77 f90 f95 f03 f08 for ftn"],
  ["fsharp", "fs fsi fsx fsscript"],
  ["gdscript", "gd"],
  ["gleam", "gleam"],
  ["go", "go"],
  ["groovy", "groovy gvy gy gsh"],
  ["haskell", "hs lhs hsc"],
  ["haxe", "hx hxml"],
  ["java", "java jsp"],
  ["julia", "jl"],
  ["kotlin", "kt kts"],
  ["livescript", "ls"],
  ["lua", "lua"],
  ["luau", "luau"],
  ["matlab", "mlx"],
  ["metal", "metal"],
  ["nasm", "nasm"],
  ["nim", "nim nims"],
  ["objectiveC", "m"],
  ["ocaml", "ml mli mll mly"],
  ["odin", "odin"],
  ["pascal", "pas lpr"],
  ["perl", "pl pm plx psgi"],
  ["php", "php phtml php3 php4 php5 php7 php8 phps"],
  ["python", "py pyw pyz"],
  ["pythonStub", "pyi"],
  ["r", "r"],
  ["racket", "rkt rktl"],
  ["raku", "raku rakumod rakutest p6 pl6 pm6"],
  ["reason", "re rei"],
  ["rescript", "res resi"],
  ["ruby", "rb rbw rbs"],
  ["rust", "rs"],
  ["scala", "scala sc"],
  ["scheme", "scm ss sld"],
  ["shader", "glsl vert frag geom tesc tese comp fx"],
  ["solidity", "sol"],
  ["swift", "swift"],
  ["systemVerilog", "sv svh"],
  ["tcl", "tcl tk"],
  ["v", "v vh"],
  ["vhdl", "vhd vhdl"],
  ["visualBasic", "vb vbs bas"],
  ["vyper", "vy"],
  ["webassembly", "wasm wat wast"],
  ["zig", "zig zon"],
  ["gdscript", "gdshader"],

  // JavaScript and TypeScript
  ["javascript", "js mjs cjs es6 es"],
  ["javascriptMin", "min.js min.mjs"],
  ["typescript", "ts mts cts"],
  ["typescriptDeclaration", "d.ts d.mts d.cts"],
  ["jsx", "jsx"],
  ["tsx", "tsx"],
  ["typescriptTest", "test.ts spec.ts test.mts spec.mts test.cts spec.cts e2e.ts"],
  ["javascriptTest", "test.js spec.js test.mjs spec.mjs test.cjs spec.cjs e2e.js"],
  ["reactTest", "test.tsx spec.tsx test.jsx spec.jsx"],
  ["storybook", "stories.ts stories.tsx stories.js stories.jsx stories.mdx story.tsx story.jsx"],
  ["sourceMap", "map"],
  ["jsConfig", "config.js config.mjs config.cjs"],
  ["tsConfig", "config.ts config.mts config.cts"],

  // Web
  ["html", "html htm xhtml shtml xht"],
  ["astro", "astro"],
  ["svelte", "svelte"],
  ["vue", "vue"],
  ["mdx", "mdx"],
  ["erb", "erb rhtml"],
  ["ejs", "ejs"],
  ["haml", "haml"],
  ["handlebars", "hbs handlebars"],
  ["jinja", "jinja jinja2 j2"],
  ["liquid", "liquid"],
  ["marko", "marko"],
  ["mjml", "mjml"],
  ["mustache", "mustache"],
  ["nunjucks", "njk nunjucks"],
  ["pug", "pug jade"],
  ["razor", "cshtml razor vbhtml"],
  ["twig", "twig"],
  ["velocity", "vm vtl"],
  ["freemarker", "ftl"],
  ["blade", "blade.php"],
  ["template", "tmpl tpl"],
  ["webShortcut", "url webloc website"],
  ["link", "lnk"],

  // Styles
  ["css", "css min.css"],
  ["cssModule", "module.css"],
  ["sass", "scss sass module.scss module.sass"],
  ["less", "less module.less"],
  ["stylus", "styl stylus"],
  ["postcss", "pcss postcss sss"],

  // Data
  ["json", "json har"],
  ["jsonLines", "jsonl ndjson"],
  ["json", "jsonc code-snippets"],
  ["json5", "json5"],
  ["jsonLd", "jsonld"],
  ["hjson", "hjson"],
  ["yaml", "yaml yml"],
  ["toml", "toml"],
  ["xml", "xml resx"],
  ["rss", "rss atom"],
  ["graphql", "graphql gql graphqls"],
  ["protobuf", "proto"],
  ["prisma", "prisma"],
  ["sql", "sql mysql ddl dml"],
  ["database", "mdf ldf frm ibd dbf realm"],
  ["sqlite", "sqlite sqlite3 db db3 s3db sl3"],
  ["access", "mdb accdb"],
  ["parquet", "parquet"],
  ["avro", "avro avsc"],
  ["arrow", "arrow feather"],
  ["binaryData", "hdf5 h5 nc cdf dat orc msgpack"],
  ["numpy", "npy npz"],
  ["pickle", "pkl pickle joblib"],
  ["rdata", "rdata rds rda"],
  ["stata", "dta do"],
  ["mapData", "gpx kml kmz shp shx osm"],
  ["jupyter", "ipynb"],
  ["rmarkdown", "rmd"],
  ["dhall", "dhall"],
  ["jsonnet", "jsonnet libsonnet"],
  ["mermaid", "mmd mermaid"],
  ["graphviz", "dot gv"],
  ["plantuml", "puml plantuml iuml"],
  ["apiBlueprint", "apib"],
  ["raml", "raml"],

  // Spreadsheets
  ["csv", "csv psv"],
  ["tsv", "tsv tab"],
  ["excel", "xls xlsx xlsm xlsb xlam"],
  ["excelTemplate", "xlt xltx xltm"],
  ["numbers", "numbers"],
  ["odfSheet", "ods ots fods"],

  // Documents
  ["word", "doc docx docm wbk"],
  ["wordTemplate", "dotx dotm"],
  ["odfText", "odt ott fodt odm"],
  ["pages", "pages"],
  ["richText", "rtf rtfd wpd wps"],
  ["xps", "xps oxps"],
  ["oneNote", "one onepkg"],
  ["project", "mpp mpt"],
  ["ebook", "epub mobi azw azw3 fb2 ibooks djvu cbz cbr"],
  ["latex", "tex ltx sty cls dtx ins latex"],
  ["bibtex", "bib bst"],
  ["postscript", "ps"],
  ["screenplay", "fountain spmd"],
  ["finalDraft", "fdx"],

  // Presentations
  ["powerpoint", "ppt pptx pptm pps ppsx ppsm"],
  ["powerpointTemplate", "pot potx potm"],
  ["keynote", "key keynote kth"],
  ["odfSlides", "odp otp fodp"],

  // PDF
  ["pdf", "pdf"],

  // Text and documentation
  ["text", "txt text nfo"],
  ["markdown", "md markdown mdown mkd mkdn mdwn mdtxt mdtext mkdown"],
  ["restructuredText", "rst rest"],
  ["asciidoc", "adoc asciidoc"],
  ["orgMode", "org"],
  ["textile", "textile"],
  ["mediawiki", "wiki mediawiki"],
  ["creole", "creole"],
  ["pod", "pod"],
  ["manpage", "man mdoc"],
  ["log", "log"],
  ["diff", "diff"],
  ["patch", "patch rej"],
  ["subtitles", "srt vtt sub ass ssa sbv ttml"],
  ["calendar", "ics ical ifb vcs"],
  ["contact", "vcf vcard"],
  ["email", "eml emlx mbox"],
  ["outlook", "msg oft pst"],
  ["prompt", "prompt prompty prompt.md prompt.txt chatmode.md"],
  ["agentInstructions", "instructions.md agent.md"],

  // Images
  ["image", "png jpg jpeg jfif pjpeg pjp gif bmp dib heic heif tif tiff jxl jp2 j2k tga dds hdr qoi pbm pgm ppm pnm pcx apng"],
  ["rawPhoto", "raw cr2 cr3 crw nef nrw arw srf sr2 dng orf rw2 raf pef x3f srw erf kdc 3fr mef mos"],
  ["iconImage", "ico icns cur"],
  ["svg", "svg svgz"],
  ["openexr", "exr"],

  // Design, 3D, CAD
  ["photoshop", "psd psb"],
  ["illustrator", "ai ait"],
  ["indesign", "indd idml indt indb"],
  ["xd", "xd"],
  ["figma", "fig figjam"],
  ["sketch", "sketch"],
  ["affinity", "afdesign af"],
  ["gimp", "xcf"],
  ["krita", "kra"],
  ["image", "procreate pxm pxd"],
  ["coreldraw", "cdr cdt"],
  ["omnigraffle", "graffle"],
  ["drawio", "drawio dio drawio.svg drawio.png"],
  ["visio", "vsd vsdx vss vssx vst vstx"],
  ["inkscape", "inkscape.svg"],
  ["model3d", "obj stl ply 3mf 3ds dae usd usdz usda usdc off wrl x3d amf"],
  ["blender", "blend blend1"],
  ["fbx", "fbx"],
  ["gltf", "gltf glb"],
  ["max3ds", "max"],
  ["maya", "ma mb"],
  ["cinema4d", "c4d"],
  ["houdini", "hip hipnc hiplc hda"],
  ["zbrush", "ztl zpr zbr"],
  ["sketchup", "skp"],
  ["rhino", "3dm"],
  ["openscad", "scad"],
  ["autocad", "dwg dxf dwf dwt"],
  ["autodesk", "f3d f3z"],
  ["cadModel", "step stp iges igs sldprt sldasm slddrw ipt iam catpart catproduct prt x_t sat"],
  ["kicad", "kicad_pcb kicad_sch kicad_pro kicad_mod kicad_sym"],
  ["eagle", "brd sch lbr"],
  ["pointCloud", "pcd las laz e57"],
  ["lightwave", "lwo lws"],
  ["unity", "unity prefab unitypackage"],
  ["unreal", "uasset umap uproject uplugin"],
  ["godotScene", "tscn tres godot escn"],
  ["pico8", "p8"],
  ["scratch", "sb2 sb3"],
  ["minecraft", "mcfunction mcmeta mcworld mcpack schem schematic"],
  ["interfaceBuilder", "xib nib"],

  // Fonts
  ["font", "ttf otf woff woff2 eot ttc otc dfont pfa pfb afm"],
  ["bitmapFont", "bdf pcf fon fnt psf"],
  ["fontforge", "sfd"],
  ["glyphs", "glyphs glyphspackage"],
  ["ufo", "ufo ufoz"],

  // Audio and video
  ["audio", "mp3 wav wave flac aac m4a m4b m4r ogg oga opus wma aiff aif aifc alac amr ape caf au snd mka ra dsf dff weba 3ga"],
  ["midi", "mid midi kar"],
  ["audacity", "aup aup3"],
  ["musescore", "mscz mscx"],
  ["lilypond", "ly ily"],
  ["video", "mp4 m4v mov qt avi webm wmv flv f4v mpg mpeg mpe m2v 3gp 3g2 ogv m2ts vob mxf rm rmvb divx asf dv hevc h264 h265 braw r3d"],
  ["matroska", "mkv mk3d"],
  ["afterEffects", "aep aet"],
  ["premiere", "prproj"],

  // Archives, packages, disk images
  ["archive", "zip 7z rar tar gz tgz bz2 tbz tbz2 xz txz lz lzma tlz zst tzst z lz4 cab arj cpio sit sitx ace zipx xar tar.gz tar.bz2 tar.xz tar.zst tar.lz tar.lz4"],
  ["brotli", "br"],
  ["installer", "rpm pkg mpkg msi msix msixbundle appx appxbundle snap flatpak appimage apkg"],
  ["javaArchive", "jar war ear"],
  ["pythonPackage", "whl egg pyd"],
  ["pythonCompiled", "pyc pyo"],
  ["rubyGem", "gem"],
  ["nugetPackage", "nupkg snupkg"],
  ["rustCrate", "crate rlib"],
  ["androidPackage", "apk aab xapk"],
  ["vscodeExtension", "vsix"],
  ["electronArchive", "asar"],
  ["diskImage", "dmg iso img toast sparseimage sparsebundle cue"],
  ["virtualMachine", "vdi ova ovf vbox vbox-extpack"],
  ["vmwareDisk", "vmdk vmx"],

  // Shells and scripts
  ["shell", "sh command tool ksh csh tcsh run"],
  ["bash", "bash"],
  ["zsh", "zsh zsh-theme"],
  ["fish", "fish"],
  ["powershell", "ps1 ps1xml pssc"],
  ["batch", "bat cmd btm"],
  ["automator", "workflow"],
  ["vim", "vim vimrc"],

  // Security
  ["certificate", "crt cer der p7b p7c p7s spc"],
  ["privateKey", "pem ppk"],
  ["publicKey", "pub"],
  ["keystore", "p12 pfx jks keystore bks truststore"],
  ["signature", "asc gpg pgp sig minisig"],
  ["passwordDatabase", "kdbx kdb 1pif keychain keychain-db"],
  ["certificate", "csr"],

  // Binaries
  ["executable", "exe com app elf out"],
  ["library", "dylib so dll lib a ko"],
  ["objectFile", "o"],
  ["binary", "bin hex rom"],
  ["backup", "bak old orig backup sav"],
  ["temporary", "tmp temp swp swo crdownload part download"],

  // Configuration
  ["config", "cfg conf config properties prefs plist reg inf cnf"],
  ["dotenv", "env"],
  ["lockfile", "lock lockb"],
  ["docker", "dockerfile containerfile"],
  ["terraform", "tf tfvars tfstate"],
  ["nomad", "nomad"],
  ["nix", "nix"],
  ["make", "mk mak make"],
  ["cmake", "cmake"],
  ["bazel", "bzl bazel"],
  ["gradle", "gradle"],
  ["sbt", "sbt"],
  ["cabal", "cabal"],
  ["dotnetProject", "sln csproj fsproj vbproj vcxproj props targets nuspec"],
  ["vscode", "code-workspace code-profile"],
  ["sublime", "sublime-project sublime-workspace sublime-settings sublime-keymap"],
  ["desktopEntry", "desktop"],
  ["finder", "ds_store"],
  ["ignore", "ignore"],
  ["kubernetes", "k8s.yaml k8s.yml"],

  // Additional types drawn by vscode-icons
  ["objectiveCpp", "mm"],
  ["hlsl", "hlsl hlsli fxh"],
  ["wgsl", "wgsl"],
  ["vba", "vba"],
  ["apex", "apex trigger"],
  ["al", "al"],
  ["ballerina", "bal"],
  ["bicep", "bicep bicepparam"],
  ["cadence", "cdc"],
  ["capnp", "capnp"],
  ["cddl", "cddl"],
  ["circom", "circom"],
  ["dylan", "dylan dyl"],
  ["grain", "gr"],
  ["huff", "huff"],
  ["idris", "idr lidr"],
  ["io", "io"],
  ["janet", "janet jdn"],
  ["k", "k"],
  ["lean", "lean"],
  ["mojo", "mojo"],
  ["nushell", "nu"],
  ["pony", "pony"],
  ["prolog", "pro prolog"],
  ["purescript", "purs"],
  ["q", "q"],
  ["qsharp", "qs"],
  ["red", "red reds"],
  ["rexx", "rexx rex"],
  ["slang", "sl"],
  ["squirrel", "nut"],
  ["teal", "tl"],
  ["toit", "toit"],
  ["uiua", "ua"],
  ["unison", "u"],
  ["vala", "vala"],
  ["vapi", "vapi"],
  ["vlang", "vsh vv"],
  ["wolfram", "wl wls nb"],
  ["wurst", "wurst"],
  ["yang", "yang"],
  ["kusto", "kql csl"],
  ["sparql", "rq sparql"],
  ["xquery", "xq xquery xqy xql"],
  ["plsql", "pls plb pck pkb pks"],
  ["pgsql", "pgsql psql"],
  ["templ", "templ"],
  ["slint", "slint"],
  ["qml", "qml qmlproject"],
  ["smarty", "smarty"],
  ["slim", "slim"],
  ["lolcode", "lol"],
  ["pawn", "pwn"],
  ["sas", "sas"],
  ["stan", "stan"],
  ["tablegen", "td"],
  ["ttcn", "ttcn ttcn3"],
  ["lsl", "lsl"],
  ["maxscript", "ms mcr"],
  ["powerQuery", "pq"],
  ["powerbi", "pbix pbit"],
  ["nearley", "ne"],
  ["lark", "lark"],
  ["antlr", "g4"],
  ["yacc", "y yy"],
  ["lex", "l lex"],
  ["flatbuffers", "fbs"],
  ["dbml", "dbml"],
  ["edge", "edge"],
  ["tera", "tera"],
  ["vento", "vto"],
  ["glimmer", "gjs gts"],
  ["imba", "imba"],
  ["riot", "riot"],
  ["san", "san"],
  ["uvue", "uvue"],
  ["wxml", "wxml"],
  ["wxss", "wxss"],
  ["dust", "dust"],
  ["jbuilder", "jbuilder"],
  ["vanillaExtract", "css.ts"],
  ["cssMap", "css.map"],
  ["jsMap", "js.map mjs.map cjs.map"],
  ["jestSnapshot", "snap"],
  ["tsBuildInfo", "tsbuildinfo"],
  ["cypressSpec", "cy.ts cy.js cy.tsx cy.jsx"],
  ["ngComponent", "component.ts"],
  ["ngComponentJs", "component.js"],
  ["ngComponentHtml", "component.html"],
  ["ngComponentCss", "component.css"],
  ["ngComponentScss", "component.scss"],
  ["ngComponentLess", "component.less"],
  ["ngComponentSass", "component.sass"],
  ["ngService", "service.ts"],
  ["ngModule", "module.ts"],
  ["ngDirective", "directive.ts"],
  ["ngPipe", "pipe.ts"],
  ["ngGuard", "guard.ts"],
  ["ngRouting", "routing.ts routing.module.ts routes.ts"],
  ["ngInterceptor", "interceptor.ts"],
  ["jsonSchema", "schema.json"],
  ["geojson", "geojson topojson"],
  ["safetensors", "safetensors"],
  ["duckdb", "duckdb"],
  ["cypher", "cypher cql"],
  ["sqlProject", "sqlproj"],
  ["xsl", "xsl xslt"],
  ["dtd", "dtd"],
  ["xml", "xsd"],
  ["xliff", "xlf xliff"],
  ["xaml", "xaml"],
  ["odfDrawing", "odg otg fodg"],
  ["odfFormula", "odf"],
  ["odfDatabase", "odb"],
  ["infopath", "xsn"],
  ["eps", "eps"],
  ["quarto", "qmd"],
  ["http", "http"],
  ["rest", "rest"],
  ["hurl", "hurl"],
  ["bruno", "bru"],
  ["ron", "ron"],
  ["registry", "reg"],
  ["systemd", "service timer socket mount automount target slice"],
  ["ovpn", "ovpn"],
  ["gettext", "po pot mo"],
  ["hunspell", "dic aff"],
  ["godotUid", "uid"],
  ["shaderlab", "shader"],
  ["n64", "n64 z64 v64"],
  ["gcode", "gcode gco"],
  ["fritzing", "fzz fzpz"],
  ["gamemaker", "yyp gml"],
  ["aseprite", "ase aseprite"],
  ["excalidraw", "excalidraw excalidraw.json excalidraw.svg excalidraw.png"],
  ["affinityPhoto", "afphoto"],
  ["affinityPublisher", "afpub"],
  ["flashSource", "fla"],
  ["flash", "swf"],
  ["javaClass", "class"],
  ["debian", "deb udeb"],
  ["bats", "bats"],
  ["powershellModule", "psm1"],
  ["powershellData", "psd1"],
  ["powershellFormat", "format.ps1xml"],
  ["powershellTypes", "types.ps1xml"],
  ["ini", "ini"],
  ["poml", "poml"],
  ["avif", "avif"],
  ["webp", "webp"],
  ["opentofu", "tofu"],
  ["hcl", "hcl"],
  ["packer", "pkr.hcl pkr.json"],
  ["ninja", "ninja"],
  ["manifest", "webmanifest manifest"],
  ["xcode", "pbxproj xcconfig xcscheme xcworkspacedata entitlements"],
  ["storyboard", "storyboard"],
  ["wasp", "wasp"],
];

// ---------------------------------------------------------------------------
// Exact file names (compared case-insensitively). Exact names beat extensions.
// ---------------------------------------------------------------------------

const fileNameGroups: Array<[IconKind, string]> = [
  // Instructions and project documents
  ["agentInstructions", "agents.md agent.md agents.override.md"],
  ["claudeInstructions", "claude.md claude.local.md"],
  ["copilotInstructions", "copilot-instructions.md"],
  ["cursorRules", ".cursorrules .cursorignore .cursorindexingignore"],
  ["skill", "skill.md"],
  ["mcpConfig", ".mcp.json mcp.json"],
  ["llmsText", "llms.txt llms-full.txt"],
  ["readme", "readme readme.md readme.txt readme.rst readme.markdown readme.adoc readme.org readme.html readme.1st read.me"],
  ["license", "license license.md license.txt license-mit license-apache licence licence.md licence.txt copying copying.md copying.txt copying.lesser notice notice.md notice.txt third_party_notices.md third-party-notices.md thirdpartynotices.txt"],
  ["changelog", "changelog changelog.md changelog.txt changes changes.md changes.txt history.md news news.md release_notes.md releases.md"],
  ["contributing", "contributing contributing.md contributing.txt"],
  ["codeOfConduct", "code_of_conduct.md code-of-conduct.md"],
  ["security", "security.md security.txt"],
  ["authors", "authors authors.md authors.txt contributors contributors.md maintainers maintainers.md credits credits.md backers.md"],
  ["todo", "todo todo.md todo.txt"],
  ["robots", "robots.txt"],

  // Git and repository settings
  ["git", ".gitignore .gitattributes .gitmodules .gitkeep .git-blame-ignore-revs .mailmap .gitconfig .gitmessage"],
  ["mercurial", ".hgignore .hgrc .hgtags"],
  ["codeowners", "codeowners owners"],
  ["dependabot", "dependabot.yml dependabot.yaml"],
  ["ignore", ".work-foldignore .ignore .rgignore .agignore .fdignore .slugignore .vercelignore"],
  ["editorconfig", ".editorconfig"],

  // JavaScript ecosystem
  ["npm", "package.json"],
  ["npmConfig", ".npmrc .npmignore"],
  ["npmLock", "package-lock.json npm-shrinkwrap.json"],
  ["yarn", "yarn.lock .yarnrc .yarnrc.yml .yarnclean"],
  ["pnpm", "pnpm-lock.yaml pnpm-workspace.yaml .pnpmfile.cjs"],
  ["bun", "bun.lockb bun.lock"],
  ["deno", "deno.json deno.jsonc deno.lock"],
  ["node", ".nvmrc .node-version"],
  ["tsConfig", "tsconfig.json jsconfig.json"],
  ["babel", ".babelrc .babelrc.json .babelrc.js .babelrc.cjs .babelrc.mjs"],
  ["swc", ".swcrc"],
  ["prettier", ".prettierrc .prettierrc.json .prettierrc.json5 .prettierrc.yaml .prettierrc.yml .prettierrc.toml .prettierrc.js .prettierrc.cjs .prettierrc.mjs .prettierrc.ts .prettierignore"],
  ["eslint", ".eslintrc .eslintrc.json .eslintrc.js .eslintrc.cjs .eslintrc.yaml .eslintrc.yml .eslintignore .eslintcache"],
  ["stylelint", ".stylelintrc .stylelintrc.json .stylelintrc.yaml .stylelintrc.yml .stylelintrc.js .stylelintrc.cjs .stylelintignore"],
  ["biome", "biome.json biome.jsonc"],
  ["browserslist", ".browserslistrc browserslist"],
  ["mocha", ".mocharc .mocharc.json .mocharc.yaml .mocharc.yml .mocharc.js .mocharc.cjs"],
  ["istanbul", ".nycrc .nycrc.json .nycrc.yaml .nycrc.yml"],
  ["commitlint", ".commitlintrc .commitlintrc.json .commitlintrc.yaml .commitlintrc.yml .commitlintrc.js"],
  ["lefthook", "lefthook.yml lefthook.yaml .lefthook.yml lefthook-local.yml"],
  ["precommit", ".pre-commit-config.yaml .pre-commit-config.yml .pre-commit-hooks.yaml"],
  ["renovate", "renovate.json renovate.json5 .renovaterc .renovaterc.json"],
  ["markdownlint", ".markdownlint.json .markdownlint.jsonc .markdownlint.yaml .markdownlint.yml .markdownlintrc .markdownlintignore .markdownlint-cli2.jsonc"],
  ["yamllint", ".yamllint .yamllint.yaml .yamllint.yml"],
  ["shellcheck", ".shellcheckrc shellcheckrc"],
  ["clang", ".clang-format .clang-tidy .clangd"],
  ["angular", "angular.json .angular-cli.json"],
  ["turborepo", "turbo.json"],
  ["nx", "nx.json"],
  ["lerna", "lerna.json"],
  ["nodemon", "nodemon.json"],
  ["pm2", "ecosystem.config.js ecosystem.config.cjs pm2.json"],
  ["vercel", "vercel.json now.json .vercel.json"],
  ["netlify", "netlify.toml _redirects _headers"],
  ["firebase", "firebase.json .firebaserc firestore.rules firestore.indexes.json storage.rules database.rules.json"],
  ["cloudflare", "wrangler.toml wrangler.json wrangler.jsonc"],
  ["watchman", ".watchmanconfig"],
  ["husky", ".huskyrc .huskyrc.json"],

  // Containers, infrastructure, and CI
  ["docker", "dockerfile containerfile"],
  ["dockerCompose", "docker-compose.yml docker-compose.yaml compose.yml compose.yaml docker-compose.override.yml docker-compose.override.yaml"],
  ["dockerIgnore", ".dockerignore .containerignore"],
  ["kubernetes", "kustomization.yaml kustomization.yml skaffold.yaml"],
  ["helm", "chart.yaml chart.lock values.yaml .helmignore"],
  ["terraform", ".terraform.lock.hcl .terraformrc terraform.rc"],
  ["ansible", "ansible.cfg .ansible-lint playbook.yml"],
  ["vagrant", "vagrantfile"],
  ["nix", "flake.nix flake.lock default.nix shell.nix"],
  ["travis", ".travis.yml"],
  ["gitlab", ".gitlab-ci.yml"],
  ["azurePipelines", "azure-pipelines.yml azure-pipelines.yaml"],
  ["jenkins", "jenkinsfile"],
  ["codecov", "codecov.yml .codecov.yml codecov.yaml"],
  ["sentry", ".sentryclirc sentry.properties"],
  ["snyk", ".snyk"],
  ["sonarqube", "sonar-project.properties"],
  ["serverless", "serverless.yml serverless.yaml serverless.ts"],
  ["heroku", "procfile"],
  ["nginx", "nginx.conf"],
  ["caddy", "caddyfile"],
  ["apache", ".htaccess httpd.conf"],
  ["devcontainer", "devcontainer.json .devcontainer.json"],
  ["gitpod", ".gitpod.yml .gitpod.dockerfile"],
  ["tilt", "tiltfile"],
  ["goreleaser", ".goreleaser.yml .goreleaser.yaml goreleaser.yml"],
  ["dvc", "dvc.yaml dvc.lock .dvcignore"],
  ["readthedocs", ".readthedocs.yml .readthedocs.yaml mkdocs.yml mkdocs.yaml"],
  ["jekyll", "_config.yml _config.yaml"],
  ["hugo", "hugo.toml hugo.yaml hugo.json"],

  // Build systems and package managers
  ["make", "makefile gnumakefile bsdmakefile"],
  ["cmake", "cmakelists.txt cmakecache.txt cmakepresets.json cmakeuserpresets.json"],
  ["meson", "meson.build meson_options.txt meson.options"],
  ["bazel", "build build.bazel workspace workspace.bazel module.bazel module.bazel.lock .bazelrc"],
  ["justfile", "justfile .justfile"],
  ["gradle", "build.gradle build.gradle.kts settings.gradle settings.gradle.kts gradle.properties gradlew gradlew.bat"],
  ["maven", "pom.xml mvnw mvnw.cmd"],
  ["sbt", "build.sbt"],
  ["leiningen", "project.clj"],
  ["clojure", "deps.edn bb.edn"],
  ["cargo", "cargo.toml"],
  ["cargoLock", "cargo.lock"],
  ["rustToolchain", "rust-toolchain rust-toolchain.toml rustfmt.toml .rustfmt.toml clippy.toml"],
  ["goModule", "go.mod"],
  ["goSum", "go.sum"],
  ["pythonConfig", "pyproject.toml setup.py setup.cfg .flake8 .pylintrc pylintrc .coveragerc manage.py"],
  ["pythonRequirements", "requirements.txt requirements-dev.txt requirements-test.txt dev-requirements.txt constraints.txt requirements.in"],
  ["pythonVersion", ".python-version"],
  ["pytest", "pytest.ini conftest.py"],
  ["pipenv", "pipfile pipfile.lock"],
  ["poetry", "poetry.lock poetry.toml"],
  ["uv", "uv.lock uv.toml"],
  ["conda", "environment.yml environment.yaml .condarc"],
  ["rubyVersion", ".ruby-version .ruby-gemset"],
  ["bundler", "gemfile gemfile.lock gems.rb gems.locked"],
  ["rake", "rakefile"],
  ["rubocop", ".rubocop.yml .rubocop_todo.yml"],
  ["rspecConfig", ".rspec"],
  ["rubyConfig", "config.ru .irbrc .pryrc"],
  ["gemConfig", ".gemrc"],
  ["cocoapods", "podfile podfile.lock"],
  ["carthage", "cartfile cartfile.resolved"],
  ["swiftPackage", "package.swift package.resolved .swiftlint.yml .swift-version .swiftformat"],
  ["composer", "composer.json composer.lock"],
  ["mix", "mix.exs mix.lock"],
  ["rebar", "rebar.config rebar.lock"],
  ["haskellConfig", "stack.yaml stack.yaml.lock package.yaml hie.yaml"],
  ["cabal", "cabal.project"],
  ["flutter", "pubspec.yaml pubspec.lock analysis_options.yaml"],
  ["homebrew", "brewfile brewfile.lock.json"],
  ["dotnetProject", "global.json nuget.config directory.build.props directory.build.targets directory.packages.props"],

  // Shells and editors
  ["bashConfig", ".bashrc .bash_profile .bash_login .bash_logout .bash_aliases .bash_history .profile"],
  ["zshConfig", ".zshrc .zshenv .zprofile .zlogin .zlogout .zsh_history"],
  ["fish", "config.fish"],
  ["vim", ".vimrc .gvimrc _vimrc .viminfo .ideavimrc .exrc"],
  ["tmux", ".tmux.conf tmux.conf"],
  ["curlConfig", ".curlrc"],
  ["wgetConfig", ".wgetrc"],
  ["finder", ".ds_store .localized"],
  ["config", "thumbs.db desktop.ini .tool-versions .inputrc"],

  // Security
  ["sshKey", "id_rsa id_dsa id_ecdsa id_ed25519 id_rsa.pub id_dsa.pub id_ecdsa.pub id_ed25519.pub known_hosts authorized_keys"],
  ["credentials", ".netrc .htpasswd credentials .pgpass .git-credentials"],

  // Front-end config files with conventional names
  ["vite", "vite.config.js vite.config.mjs vite.config.cjs vite.config.ts vite.config.mts vite.config.cts"],

  // Additional names drawn by vscode-icons
  ["geminiInstructions", "gemini.md"],
  ["coderabbit", ".coderabbit.yaml .coderabbit.yml"],
  ["opencode", "opencode.json opencode.jsonc"],
  ["unlicense", "unlicense unlicense.md unlicense.txt"],
  ["humans", "humans.txt"],
  ["sitemap", "sitemap.xml"],
  ["gcloud", ".gcloudignore app.yaml cloudbuild.yaml"],
  ["taskfile", "taskfile.yml taskfile.yaml taskfile.dist.yml"],
  ["earthly", "earthfile"],
  ["taplo", ".taplo.toml taplo.toml"],
  ["cspell", "cspell.json .cspell.json cspell.config.yaml cspell.config.js cspell.yaml"],
  ["commitizen", ".cz.toml .czrc .cz.json cz.json"],
  ["semanticRelease", ".releaserc .releaserc.json .releaserc.yaml .releaserc.yml .releaserc.js release.config.js release.config.cjs"],
  ["knip", "knip.json knip.jsonc .knip.json knip.config.ts"],
  ["syncpack", ".syncpackrc .syncpackrc.json .syncpackrc.yaml syncpack.config.js"],
  ["stryker", "stryker.conf.js stryker.conf.json stryker.config.json stryker.config.mjs"],
  ["wallaby", "wallaby.js wallaby.conf.js"],
  ["testcafe", ".testcaferc.json .testcaferc.js"],
  ["tslint", "tslint.json tslint.yaml"],
  ["jshint", ".jshintrc .jshintignore"],
  ["jsbeautify", ".jsbeautifyrc .jsbeautify"],
  ["htmlhint", ".htmlhintrc"],
  ["csscomb", ".csscomb.json"],
  ["csslint", ".csslintrc"],
  ["coffeelint", "coffeelint.json .coffeelintignore"],
  ["textlint", ".textlintrc .textlintrc.json .textlintignore"],
  ["markuplint", ".markuplintrc .markuplintrc.json"],
  ["vale", ".vale.ini vale.ini"],
  ["doxygen", "doxyfile"],
  ["typedoc", "typedoc.json typedoc.jsonc"],
  ["tsdoc", "tsdoc.json"],
  ["eleventy", ".eleventy.js .eleventyignore"],
  ["ionic", "ionic.config.json .io-config.json"],
  ["tauri", "tauri.conf.json tauri.conf.json5 tauri.config.json"],
  ["electronBuilder", "electron-builder.yml electron-builder.json electron-builder.json5 forge.config.js forge.config.ts"],
  ["eas", "eas.json"],
  ["sequelize", ".sequelizerc"],
  ["convex", "convex.json"],
  ["parcel", ".parcelrc"],
  ["flyio", "fly.toml"],
  ["railway", "railway.json railway.toml"],
  ["renderConfig", "render.yaml"],
  ["codemagic", "codemagic.yaml codemagic.yml"],
  ["bitbucket", "bitbucket-pipelines.yml bitbucket-pipelines.yaml"],
  ["appveyor", "appveyor.yml .appveyor.yml"],
  ["drone", ".drone.yml .drone.yaml"],
  ["trivy", "trivy.yaml trivy.yml .trivyignore"],
  ["checkov", ".checkov.yml .checkov.yaml"],
  ["mise", "mise.toml .mise.toml mise.local.toml .mise.local.toml"],
  ["direnv", ".envrc"],
  ["devenv", "devenv.nix devenv.yaml devenv.lock"],
  ["doppler", "doppler.yaml doppler-template.yaml"],
  ["funding", "funding.yml"],
  ["publiccode", "publiccode.yml publiccode.yaml"],
  ["reuse", "reuse.toml dep5"],
  ["allContributors", ".all-contributorsrc"],
  ["godotProject", "project.godot"],
  ["dbt", "dbt_project.yml"],
  ["pulumi", "pulumi.yaml pulumi.yml"],
  ["pixi", "pixi.toml pixi.lock"],
  ["pdm", "pdm.lock pdm.toml .pdm-python"],
  ["ruff", "ruff.toml .ruff.toml"],
  ["mypy", "mypy.ini .mypy.ini"],
  ["tox", "tox.ini"],
  ["bazelIgnore", ".bazelignore"],
  ["bazelVersion", ".bazelversion"],
  ["goWork", "go.work go.work.sum"],
  ["golangci", ".golangci.yml .golangci.yaml .golangci.toml .golangci.json"],
  ["buf", "buf.yaml buf.gen.yaml buf.work.yaml buf.lock"],
  ["bunfig", "bunfig.toml"],
  ["rome", "rome.json"],
  ["oxlint", ".oxlintrc.json oxlintrc.json"],
  ["jsr", "jsr.json jsr.jsonc"],
  ["lintStaged", ".lintstagedrc .lintstagedrc.json .lintstagedrc.yaml .lintstagedrc.yml .lintstagedrc.js .lintstagedrc.cjs .lintstagedrc.mjs"],
  ["nanostaged", ".nanostagedrc .nano-staged.json nano-staged.json"],
  ["prismaConfig", "prisma.config.ts"],
  ["graphqlConfig", ".graphqlrc .graphqlrc.json .graphqlrc.yaml .graphqlrc.yml graphql.config.js graphql.config.ts"],
  ["codegen", "codegen.yml codegen.yaml codegen.ts codegen.json"],
  ["npmPackageJsonLint", ".npmpackagejsonlintrc.json npmpackagejsonlint.config.js"],
  ["changelogen", ".changelogrc changelog.config.js"],
  ["vscodeTest", ".vscode-test.js .vscode-test.mjs .vscode-test.cjs"],
  ["nestjs", "nest-cli.json .nestcli.json nest.json"],
  ["expo", "app.config.js app.config.ts"],
  ["denoify", "denoify.config.json"],
  ["manifest", "manifest.json site.webmanifest"],
  ["openapi", "openapi.yaml openapi.yml openapi.json swagger.json swagger.yaml swagger.yml"],
  ["xcode", "project.pbxproj"],
];

// Config families matched by a file-name stem, ignoring the trailing script
// extension (`vite.config.ts`, `jest.config.mjs`, `tsconfig.app.json` ...).
const fileNamePatterns: Array<[RegExp, IconKind]> = [
  [/^\.env(\..+)?$/, "dotenv"],
  [/^(\w+\.)?env\.example$/, "dotenv"],
  [/^tsconfig\..+\.json$/, "tsConfig"],
  [/^jsconfig\..+\.json$/, "jsConfig"],
  [/^vite(\.\w+)?\.config\.[cm]?[jt]s$/, "vite"],
  [/^vitest(\.\w+)?\.(config|workspace)\.[cm]?[jt]s$/, "vitest"],
  [/^webpack(\.\w+)*\.(config|conf)\.[cm]?[jt]s$/, "webpack"],
  [/^rollup(\.\w+)?\.config\.[cm]?[jt]s$/, "rollup"],
  [/^esbuild(\.\w+)?\.config\.[cm]?[jt]s$/, "esbuild"],
  [/^babel\.config\.(json|[cm]?[jt]s)$/, "babel"],
  [/^tailwind(\.\w+)?\.config\.[cm]?[jt]s$/, "tailwind"],
  [/^postcss\.config\.[cm]?[jt]s$|^\.postcssrc(\.\w+)?$/, "postcssConfig"],
  [/^jest(\.\w+)?\.config\.(json|[cm]?[jt]s)$/, "jest"],
  [/^playwright(\.\w+)?\.config\.[cm]?[jt]s$/, "playwright"],
  [/^cypress\.config\.[cm]?[jt]s$|^cypress\.json$/, "cypress"],
  [/^karma\.conf\.[cm]?[jt]s$/, "karma"],
  [/^prettier\.config\.[cm]?[jt]s$/, "prettier"],
  [/^eslint\.config\.[cm]?[jt]s$/, "eslint"],
  [/^stylelint\.config\.[cm]?[jt]s$/, "stylelint"],
  [/^commitlint\.config\.[cm]?[jt]s$/, "commitlint"],
  [/^next\.config\.[cm]?[jt]s$/, "nextjs"],
  [/^nuxt\.config\.[cm]?[jt]s$/, "nuxt"],
  [/^remix\.config\.[cm]?[jt]s$/, "remix"],
  [/^gatsby-(config|node|browser|ssr)\.[cm]?[jt]sx?$/, "gatsby"],
  [/^svelte\.config\.[cm]?[jt]s$/, "svelteConfig"],
  [/^astro\.config\.[cm]?[jt]s$/, "astroConfig"],
  [/^vue\.config\.[cm]?[jt]s$/, "vueConfig"],
  [/^lint-staged\.config\.[cm]?[jt]s$/, "lintStaged"],
  [/^wdio(\.\w+)?\.conf\.[cm]?[jt]s$/, "wdio"],
  [/^docusaurus\.config\.[cm]?[jt]s$/, "docusaurus"],
  [/^eleventy\.config\.[cm]?[jt]s$/, "eleventy"],
  [/^quasar\.config\.[cm]?[jt]s$/, "quasar"],
  [/^capacitor\.config\.([cm]?[jt]s|json)$/, "capacitor"],
  [/^uno\.config\.[cm]?[jt]s$/, "unocss"],
  [/^windi\.config\.[cm]?[jt]s$/, "windi"],
  [/^panda\.config\.[cm]?[jt]s$/, "pandacss"],
  [/^tamagui\.config\.[cm]?[jt]s$/, "tamagui"],
  [/^drizzle\.config\.[cm]?[jt]s$/, "drizzle"],
  [/^knexfile\.[cm]?[jt]s$/, "knex"],
  [/^rspack\.config\.[cm]?[jt]s$/, "rspack"],
  [/^rolldown\.config\.[cm]?[jt]s$/, "rolldown"],
  [/^tsdown\.config\.[cm]?[jt]s$/, "tsdown"],
  [/^craco\.config\.[cm]?[jt]s$/, "craco"],
  [/^metro\.config\.[cm]?[jt]s$/, "metro"],
  [/^purgecss\.config\.[cm]?[jt]s$/, "purgecss"],
  [/^svgo\.config\.[cm]?[jt]s$/, "svgo"],
  [/^dockerfile[.-].+$/, "docker"],
  [/^(docker-)?compose\..+\.ya?ml$/, "dockerCompose"],
  [/^requirements[-_.].*\.txt$/, "pythonRequirements"],
  [/^readme[._-].+$/, "readme"],
  [/^(license|licence|copying)[._-].+$/, "license"],
  [/^changelog[._-].+$/, "changelog"],
];

// Path-aware rules for files whose meaning comes from their folder.
const pathPatterns: Array<[RegExp, IconKind]> = [
  [/(^|\/)\.github\/workflows\/[^/]+\.ya?ml$/, "githubActions"],
  [/(^|\/)\.circleci\/config\.ya?ml$/, "circleci"],
  [/(^|\/)\.husky\/[^/]+$/, "husky"],
  [/(^|\/)\.storybook\/[^/]+$/, "storybookConfig"],
  [/(^|\/)\.devcontainer\/[^/]+\.json$/, "devcontainer"],
  [/(^|\/)\.vscode\/[^/]+\.json$/, "vscode"],
  [/(^|\/)\.ssh\/config$/, "sshKey"],
];

// Name-based rules that are neither exact names nor plain extensions.
const nameRules: Array<[RegExp, IconKind]> = [
  // `.key` is Keynote on a Mac, but `server.key` and friends are private keys.
  [/(^|[._-])(server|private|privkey|client|tls|ssl|localhost|domain|ca|signing|id_[a-z0-9]+)([._-][^.]*)?\.key$/, "privateKey"],
  [/_test\.go$/, "goTest"],
  [/^test_.+\.py$|_test\.py$/, "pythonTest"],
  [/_spec\.rb$/, "rubySpec"],
  [/^tests?\.rs$/, "rustTest"],
];

const fileNameIconMap = new Map<string, FileTreeIconSpec>();
for (const [kind, names] of fileNameGroups) {
  for (const name of names.split(/\s+/)) fileNameIconMap.set(name, kinds[kind]);
}

const extensionIconMap = new Map<string, FileTreeIconSpec>();
let longestExtensionParts = 1;
for (const [kind, extensions] of extensionGroups) {
  for (const extension of extensions.split(/\s+/)) {
    extensionIconMap.set(extension, kinds[kind]);
    longestExtensionParts = Math.max(longestExtensionParts, extension.split(".").length);
  }
}

export function fileTreeFileIcon(path: string): FileTreeIconSpec {
  const normalizedPath = path.replace(/\\/g, "/").toLowerCase();
  const name = baseName(normalizedPath);
  const exact = fileNameIconMap.get(name);
  if (exact) return exact;
  for (const [pattern, kind] of pathPatterns) if (pattern.test(normalizedPath)) return kinds[kind];
  for (const [pattern, kind] of fileNamePatterns) if (pattern.test(name)) return kinds[kind];
  for (const [pattern, kind] of nameRules) if (pattern.test(name)) return kinds[kind];
  return extensionIcon(name) ?? fallbackFileIcon;
}

/** Every folder gets the same plain glyph; the name never changes it. */
export function fileTreeFolderIcon(_pathOrName: string, expanded: boolean): FileTreeIconSpec {
  return expanded ? openFolderIcon : closedFolderIcon;
}

export function fileTreeIconGlyph(iconSpec: FileTreeIconSpec): FileIconGlyph {
  return fileIconGlyphs[iconSpec.glyph] ?? fileIconGlyphs[fallbackFileIcon.glyph]!;
}

/** All icon specs the resolver can return (for tests and the generator). */
export function allFileTreeIconSpecs(): FileTreeIconSpec[] {
  return [fallbackFileIcon, closedFolderIcon, openFolderIcon, ...Object.values(kinds)];
}

function extensionIcon(name: string): FileTreeIconSpec | undefined {
  // A leading dot marks a hidden file, not an extension: `.bashrc` has the
  // extension `bashrc`, while `notes` has none.
  const parts = name.replace(/^\.+/, "").split(".");
  if (parts.length < 2 && !name.startsWith(".")) return undefined;
  const firstExtensionIndex = name.startsWith(".") && parts.length === 1 ? 0 : 1;
  const longest = Math.min(longestExtensionParts, parts.length - firstExtensionIndex);
  for (let count = longest; count >= 1; count -= 1) {
    const match = extensionIconMap.get(parts.slice(parts.length - count).join("."));
    if (match) return match;
  }
  return undefined;
}

function baseName(path: string): string {
  return path.split("/").filter(Boolean).pop() ?? path;
}
